thisdot/starter.dev-github-showcases

- angular-ngrx-scss/src/app/auth/services/auth.service.spec.ts
Tests for the auth service were flaky because one of the tests was mutating global state, but tests are not guaranteed to always run in-order as they are defined (this is determined by the seed). I reset the token value in auth.service.spec.ts so it's reset before each test is run to avoid the flakiness.
> [Angular - NgRx - SCSS] Fix Flaky Auth Karma Tests

- starter-dev-backend/package.json
- starter-dev-backend/serverless.yml
- starter-dev-backend/yarn.lock
Behind the scenes, I had to manually deploy the API via the migration strategy as we changed API types under the hood. I followed this guide in particular https://github.com/amplify-education/serverless-domain-manager#changing-api-types. I have successfully deployed this API using this configuration.
Specifically, the steps I took:
1. Configure an Amazon Certificate for the wildcard domain
2. `yarn add -D serverless-domain-manager`
3. Update the serverless.yaml to what's in the PR but with the additional flag `allowPathMatching` set to true so I could migrate from a REST API to a HTTP API (this is a cost savings effort)
4. Ran `sls deploy --stage production --region us-east-1`
5. Removed the `allowPathMatching` flag
If you visit `https://api.starter.dev/`, you'll see the API working …
> add and configure serverless-domain-manager

- angular-apollo-tailwind/.env.example
- angular-apollo-tailwind/src/app/auth/auth.service.ts
- angular-apollo-tailwind/src/environments/environment.ts
- starter-dev-backend/package.json
- starter-dev-backend/serverless.yml
Removed the need to specify a `/api` path at the end of a server endpoint.
Local dev:
* still proxies `/api` by default
Prod:
* will append the baseUrl to a `/api` path.
> changed env url

- angular-ngrx-scss/karma.conf.js
- angular-ngrx-scss/package-lock.json
- angular-ngrx-scss/package.json
- angular-ngrx-scss/src/app/app.component.spec.ts
- angular-ngrx-scss/src/app/home/home.component.spec.ts
- angular-ngrx-scss/src/app/home/profile/profile-nav/profile-nav.component.spec.ts
- angular-ngrx-scss/src/app/home/profile/profile.component.spec.ts
~Note that router warnings are still throwing, but those are fixed in #395. I purposely left those in to avoid merge conflicts.~
Edit: Changes from the aforementioned PR are merged, so the final test results should be accurate.
> [Angular-NgRx-SCSS] Fixed all Test Warnings

- angular-ngrx-scss/src/app/home/home.component.scss
- angular-ngrx-scss/src/app/home/top-repositories/top-repositories.component.scss
- angular-ngrx-scss/src/app/home/user-gists/user-gists.component.html
- angular-ngrx-scss/src/app/home/user-gists/user-gists.component.scss
-  accessibility: Consider using semantic HTML elements ul and li here.
-  styling: needs mobile styling (gist section should move to bottom of page on small screens, see next-react-query deployed app for example)
Closes #186
> [angular-ngrx-scss] - Gists panel improvements

- angular-apollo-tailwind/src/app/file-viewer/repo-read-me/repo-read-me.component.html
- angular-apollo-tailwind/src/app/issues/issues.component.html
- angular-apollo-tailwind/src/app/profile/profile-repos-view/profile-repos-view.component.html
- angular-apollo-tailwind/src/app/profile/profile-repos-view/profile-repos.store.ts
- angular-apollo-tailwind/src/app/pull-requests/components/pull-requests-filters/pull-requests-filters.component.ts
- angular-apollo-tailwind/src/app/pull-requests/pull-requests.component.html
- angular-apollo-tailwind/src/app/pull-requests/pull-requests.store.ts
- angular-apollo-tailwind/src/app/repos/components/user-gists/user-gists.component.html
- next-react-query-tailwind/src/components/UserGists/UserGists.data.tsx
- starter-dev-e2e/cypress/e2e/dashboard.cy.ts
- starter-dev-e2e/cypress/e2e/repo.cy.ts
- starter-dev-e2e/cypress/utils/interceptors.json
Closes #422 
Fixes a number of bugs in `Angular-Apollo-Tailwind`:
- resolve failing readme test
- hide pagination buttons when no hasNext or Previous
- resolve Labels not populating for Repo PR list
- properly set filter results count for profile repos
For both `Angular-Apollo-Tailwind` and `Next-React-Query-Tailwind`:
- Align empty gist UI (let me know if this wording should change)
Now, all Cypress tests pass! `Angular-Apollo-Tailwind` takes ~0:36, and `Next-React-Query-Tailwind` takes ~1:40 🤔
> [Cypress] Resolve failing tests

- angular-ngrx-scss/src/app/shared/components/repo-controls/repo-controls.component.html
- angular-ngrx-scss/src/app/shared/components/repo-controls/repo-controls.component.scss
- angular-ngrx-scss/src/app/shared/components/repo-controls/repo-controls.component.spec.ts
- angular-ngrx-scss/src/app/shared/components/repo-controls/repo-controls.component.ts
- angular-ngrx-scss/src/app/state/profile/profile.selectors.ts
> [angular-ngrx-scss] - Implement search/filter/sort text

- cra-rxjs-styled-components/README.md
Fixes broken link to the showcases Github repo in the README.
closes #594
> [CRA RXJS SC] fix broken link

- README.md
This PR updates the README to list all of the deployed showcases. 
closes #716
> docs: updating tables for deployed showcases

- qwik-graphql-tailwind/src/components/icons/repo.icon.tsx
- qwik-graphql-tailwind/src/routes/orgs/[name]/index.tsx
- qwik-graphql-tailwind/src/routes/orgs/[name]/org-profile-card.tsx
- qwik-graphql-tailwind/src/routes/orgs/[name]/types.ts
> feat(qwik-pod): Add org profile layout

- svelte-kit-scss/package-lock.json
- svelte-kit-scss/src/lib/components/Profile/OrgInfo/OrgInfo.svelte
- svelte-kit-scss/src/lib/components/Profile/ProfileAboutSection/ProfileAboutSection.spec.ts
- svelte-kit-scss/src/lib/components/Profile/ProfileAboutSection/ProfileAboutSection.svelte
- svelte-kit-scss/src/lib/components/Profile/ProfileNavSection/ProfileNavSection.spec.ts
- svelte-kit-scss/src/lib/components/Profile/ProfileNavSection/ProfileNavSection.svelte
- svelte-kit-scss/src/lib/components/RepoControls/RepoControls.svelte
- svelte-kit-scss/src/lib/components/RepoList/RepoList.svelte
- svelte-kit-scss/src/lib/components/RepositoryCard/RepositoryCard.svelte
- svelte-kit-scss/src/lib/components/TopRepositories/TopRepositories.svelte
- svelte-kit-scss/src/lib/helpers/index.ts
- svelte-kit-scss/src/lib/helpers/user.ts
- svelte-kit-scss/src/routes/(authenticated)/(home)/+page.server.ts
- svelte-kit-scss/src/routes/(authenticated)/(home)/+page.svelte
- svelte-kit-scss/src/routes/(authenticated)/[username]/+page.server.ts
- svelte-kit-scss/src/routes/(authenticated)/[username]/+page.svelte
Resolves: #678
User Profile result:
Org Profile result:
As a user, I can navigate to my profile page and see my profile information, as well as a list of all my repositories. I can also see options to search my repositories, sort them, and filter them. (Functionality does not need to work yet for these options, they just need to be visible.)
> [sveltekit-pod] 18 Create profile page layout

- svelte-kit-scss/.eslintrc.json
- svelte-kit-scss/.husky/pre-commit
- svelte-kit-scss/.husky/pre-push
- svelte-kit-scss/package-lock.json
- svelte-kit-scss/package.json
> # Background
> Added husky pre-commit & pre-push for automatic linting and formatting
1. Added lint-staged
2. Added lint-staged scripts with `prettier forma`t and `eslint .`
3. Added prepare command to setup husky
Things to do after PR is merged:
Make sure to run ` npm install`  to setup husky properly added by the prepare command in our `package.json`
If using vscode make sure to the auto-formatter in your vs-code `settings.json`
` "editor.defaultFormatter": "esbenp.prettier-vscode",`
` "[svelte]": { "editor.defaultFormatter": "svelte.svelte-vscode" },`
4. Husky will remind us to format our code
Happy Coding
> [Sveltekit + Scss] Add Husky to Sveltekit + SCSS

- svelte-kit-scss/src/lib/components/FileExplorer/FileExplorerAbout/FileExplorerAbout.svelte
- svelte-kit-scss/src/lib/components/FileExplorer/FileExplorerContainer/FileExplorerContainer.svelte
- svelte-kit-scss/src/lib/components/FileExplorer/FileExplorerNav/FileExplorerNav.svelte
- svelte-kit-scss/src/lib/components/FileExplorer/FileExplorerReadme/FileExplorerReadme.svelte
- svelte-kit-scss/src/lib/helpers/handleAnchorClick.ts
- svelte-kit-scss/src/lib/helpers/index.ts
- svelte-kit-scss/src/routes/(authenticated)/[username]/[repo]/+page.svelte
Resolves: #778 
Result: 
https://www.loom.com/share/389f28d9b7c44baa843cb0bead2e2ee9
> # Create single repo view about section
> 
> 
> A sub-component of the single repo page, this component focuses on the about section. It should show the user details about the repository, and any links made available to the user from that section.
> 
> 
> - [x] About title
> - [x] repo description
> - [x] link icon and url for deployed version (if available)
> - [x] open book icon and readme title
> - [x] divider line
> 
> ## Notes
>
> [sveltekit-pod] 26 Create single repo view about section

- qwik-graphql-tailwind/src/components/filter-dropdown/filter-dropdown.tsx
- qwik-graphql-tailwind/src/components/repo-filters/repo-filters.classNames.ts
- qwik-graphql-tailwind/src/components/repo-filters/repo-filters.tsx
- qwik-graphql-tailwind/src/components/user-dropdown/user-dropdown.tsx
- qwik-graphql-tailwind/src/components/user-repos/filter-sort-functions.ts
- qwik-graphql-tailwind/src/components/user-repos/user-repos.tsx
- qwik-graphql-tailwind/src/context/repo-filter.ts
- qwik-graphql-tailwind/src/routes/[user]/index.tsx
In another ticket, a component was created with the type dropdown button. The purpose of this ticket is to add the functionality and populate the fields for that button. The options that should be available to the user are listed below - when a user selects an option, the repository list on the page should be filtered to only include ones that match the user’s selection.
> [qwik-pod]:c Implement type filter functionality

- qwik-graphql-tailwind/src/components/filter-dropdown/filter-dropdown.tsx
- qwik-graphql-tailwind/src/components/repo-filters/repo-filters.classNames.ts
- qwik-graphql-tailwind/src/components/repo-filters/repo-filters.tsx
- qwik-graphql-tailwind/src/components/repo-filters/types.ts
- qwik-graphql-tailwind/src/components/user-repos/filter-sort-functions.ts
- qwik-graphql-tailwind/src/components/user-repos/user-repos.tsx
- qwik-graphql-tailwind/src/routes/[user]/index.tsx
In another ticket, a component was created with the language dropdown button. The purpose of this ticket is to add the functionality and populate the fields for that button. The options that should be available to the user are listed below - when a user selects an option, the repository list on the page should be filtered to only include ones that match the user’s selection.
> [qwik-pod]:  Implement language filter functionality

- svelte-kit-scss/src/lib/components/Profile/ProfileNavSection/ProfileNavSection.svelte
- svelte-kit-scss/src/lib/components/Repo/RepoHeader/RepoHeader.svelte
- svelte-kit-scss/src/lib/components/Repo/RepoHeader/RepoHeading/RepoHeading.svelte
- svelte-kit-scss/src/lib/components/Repo/RepoHeader/RepoInfo/RepoInfo.svelte
- svelte-kit-scss/src/lib/components/Repo/RepoHeader/RepoNavigation/RepoNavigation.svelte
- svelte-kit-scss/src/lib/components/RepositoryCard/RepositoryCard.svelte
- svelte-kit-scss/src/lib/helpers/formatting.ts
- svelte-kit-scss/src/lib/helpers/index.ts
- svelte-kit-scss/src/lib/helpers/repository.ts
- svelte-kit-scss/src/routes/(authenticated)/[username]/+page.svelte
Resolves: #782
Result: 
https://www.loom.com/share/e32a1a87c1fb42dfb3cdda234c68be56
> 
> As a user, I can view a page for an individual repository with details about that repository. I can see the about information, tabs for code / issues / pull requests, info about how many watchers / stars / forks the repo has, and view the root folder’s contents in a file tree. At the bottom of the page I can also view the contents of the main readme page.
> 
> 
> - [x] book icon with user name / repo name and visibility tag (public / private)
> - [x] buttons with icon, name, and count for: (buttons do not need to be functional)
>     - [x] watch
>     - [x] star
>     - [x] fork
> - [x] section will have three tab headers for different views (do not need to build the …
> [sveltekit-pod] 25 Create single repo view sub header

- qwik-graphql-tailwind/src/components/repo-filters/repo-filters.tsx
- qwik-graphql-tailwind/src/components/search-input/search-input.tsx
- qwik-graphql-tailwind/src/components/user-repos/user-repos.tsx
- qwik-graphql-tailwind/src/context/repo-filter.ts
- qwik-graphql-tailwind/src/routes/[user]/index.tsx
##Acceptance Criteria
Closes: #771
> feat(qwik) - Implement search text filter text

- svelte-kit-scss/src/hooks.server.ts
- svelte-kit-scss/src/lib/components/NavBar/NavBar.svelte
- svelte-kit-scss/src/lib/services/auth-service.ts
- svelte-kit-scss/src/routes/(authenticated)/[username]/+page.svelte
- svelte-kit-scss/src/routes/logout/+page.server.ts
Resolves: #783
> # Add logout functionality
> 
> 
> As a user, if I click the sign out link in the header, I am signed out of the application and redirected to the sign in screen. 
> 
> 
> - [x] connect header / nav bar button to `/logout` route
> - [x] when clicked, clear user authentication from storage
> - [x] redirect to login page on success
> 
> ## Notes
> 
> Ensure the user’s access token cookie is cleared, and any information in any state storage is cleared as well.
> [sveltekit-pod] 34 Add logout functionality

- amplify.yml
closes #698 
- We use AWS Amplify for our deployments
- If you do not have access to the AWS account, please ask a manager for access
- You should have to modify the `amplify.yaml` in the top-level directory
> feat(qwik-pod): setup app for deployment, updated the amplify.yml file

- qwik-graphql-tailwind/src/routes/[owner]/[name]/index.tsx
- qwik-graphql-tailwind/src/utils/queries/pull-request.ts
On the single repo page, we’ll have a tab for viewing open and closed pull requests. We do not (currently) have the functionality to click into the PRs, so this ticket will be for creating the initial view that mostly concerns the name of the PR and some metadata about each one.
closes #853
> [qwik-pod] : Get pull request information from GitHub API

- angular-apollo-tailwind/projects/shared/src/lib/pipes/generate-url-with-protocol/generate-url-with-protocol.pipe.spec.ts
- angular-apollo-tailwind/projects/shared/src/lib/pipes/generate-url-with-protocol/generate-url-with-protocol.pipe.ts
- angular-apollo-tailwind/projects/shared/src/lib/pipes/index.ts
- angular-apollo-tailwind/projects/shared/src/lib/pipes/pipes.module.ts
- angular-apollo-tailwind/src/app/profile/profile-about/profile-about.component.html
- angular-apollo-tailwind/src/app/profile/profile.module.ts
> fix(angular-apollo-tailwind): append protocol if missing from user url

- svelte-kit-scss/src/lib/components/IssueHeader/IssueHeader.svelte
- svelte-kit-scss/src/lib/components/IssuesList/IssuesList.svelte
- svelte-kit-scss/src/lib/helpers/issues.ts
- svelte-kit-scss/src/routes/(authenticated)/[username]/[repo]/issues/+page.server.ts
- svelte-kit-scss/src/routes/(authenticated)/[username]/[repo]/issues/+page.svelte
Resolves #859
As a user, if I click into the issues tab for a repository, I can see a list of cards containing information about issues for this repo. By default I land on the view for open issues, and can click on the words “open” or “closed” to change if I see currently open or closed issues.
> [sveltekit-pod] 30 Create single repo issues tab view

- svelte-kit-scss/vite.config.ts
Unexpected token error when building the project with some commonjs modules
if (typeof global !== 'undefined') { global.Prism = Prism; }
https://thisdot-labs.slack.com/archives/C0475BB41DW/p1668521420727819
> Fix Error occuring on build

- .github/workflows/ci-solidjs-tailwind.yml
We want to review changes in as near real-time as possible. The goal of this is to set up guard rails for development practices and validate features as they’re completed.
You can use existing [CI workflows](https://github.com/thisdot/starter.dev-github-showcases/tree/main/.github/workflows) as a baseline
> chore: workflow added

- solidjs-tailwind/src/services/get-issues.js
- solidjs-tailwind/src/services/queries/issue-info.js
On the single repo page, we’ll have a tab for viewing open and closed issues. We do not (currently) have the functionality to click into the issues, so this ticket will be for creating the initial view that mostly concerns the name of the issue and some metadata about each one.
> feat(solid-kit): Get issue information from GitHub API

- solidjs-tailwind/src/components/Icons/BookOpenIcon.jsx
- solidjs-tailwind/src/components/Icons/index.js
- solidjs-tailwind/src/components/RepoAbout/Description.jsx
- solidjs-tailwind/src/components/RepoAbout/HomePageUrl.jsx
- solidjs-tailwind/src/components/RepoAbout/RepoAbout.jsx
- solidjs-tailwind/src/components/RepoAbout/RepoAbout.module.css
- solidjs-tailwind/src/components/RepoAbout/RepoAbout.stories.jsx
- solidjs-tailwind/src/components/RepoAbout/Topics.jsx
- solidjs-tailwind/src/components/RepoAbout/index.jsx
Closes: https://github.com/thisdot/starter.dev-github-showcases/issues/942
A sub-component of the single repo page, this component focuses on the about section. It should show the user details about the repository, and any links made available to the user from that section.
> created component for the about section

- svelte-kit-scss/package.json
Remove links to the showcase for the sveltekit kit, at least until the showcase is ready and deployed
> chore [sveltekit-pod]: disable showcase link for sveltekit

- svelte-kit-scss/src/lib/components/IssueSearch/IssueSearchListItem/IssueSearchAssignees.svelte
Resolves: #967
> File: svelte-kit-scss/src/lib/components/IssueSearch/IssueSearchListItem/IssueSearchAssignees.svelte
> - look into removing the `!important` from the `margin-right` property
> `!important` is almost never the right solution. It has overreaching implications of overriding user styles and limits the ability to override styles in the future. Since this is a showcase app, showing our expertise is important, and I don't think `!important` in the CSS reflects well on us.
> [sveltekit-pod] IssueSearchAssignees.svelte: Remove !important from SCSS

- svelte-kit-scss/src/lib/components/shared/Dropdown/DropdownMenuSelect/DropdownMenuSelect.svelte
- svelte-kit-scss/src/lib/components/shared/Dropdown/item-templates/DropdownItemTemplateCheckbox.svelte
Resolves: #969
> File: svelte-kit-scss/src/lib/components/shared/Dropdown/item-templates/DropdownItemTemplateCheckbox.svelte
>    + related files if required
> - I think we need to add some aria listbox attributes to this custom multi select dropdown
> - https://www.w3.org/TR/wai-aria-1.1/#listbox
> This will demonstrate our commitment to accessibility and show that we are aware of it in our showcases.
>
> [sveltekit-pod] Dropdown: Add aria-attributes to our custom multiselect dropdown

- solidjs-tailwind/src/components/RepoHeading/PrivacyIcon.jsx
- solidjs-tailwind/src/components/RepoHeading/RepoHeading.jsx
- solidjs-tailwind/src/components/RepoHeading/RepoHeading.module.css
- solidjs-tailwind/src/components/RepoHeading/RepoHeading.stories.jsx
- solidjs-tailwind/src/components/RepoHeading/RepoHeading.stories.tsx
- solidjs-tailwind/src/components/RepoHeading/index.ts
This PR ports over the RepoHeading component for use in the solid showcase
- Adds RepoHeading component
- Adds PrivacyIcon component
- Adds RepoHeading css module
- Adds RepoHeading story
Closes #935
> feat(solidjs-tailwind): Adds RepoHeading Component

- svelte-kit-scss/src/lib/components/RepositoryCard/RepositoryCard.spec.ts
Resolves: #972
> File: svelte-kit-scss/src/lib/components/RepositoryCard/RepositoryCard.spec.ts
> In order to expidite merging we commented out a failing test.
> - line 38: `it('should should render repo last update', () => {` test is commented out
> Please uncomment and fix, or remove test if it is not appropriate
> [sveltekit-pod] RepositoryCard.spec.ts: Uncomment the skipped test

- angular-apollo-tailwind/src/app/components/toaster/toaster.component.html
- angular-apollo-tailwind/src/app/home/home.component.css
- angular-apollo-tailwind/src/app/home/home.component.html
- angular-apollo-tailwind/src/app/provider/provider.component.css
- angular-apollo-tailwind/src/app/provider/provider.component.html
- angular-apollo-tailwind/src/styles.css
This adds the Netlify badge (bottom of the page) to the Angular Apollo Tailwind showcase. It appears on all pages of the app (including the login screen)
This does not close the ticket #961 but checks one of its task.
> feat(#961): Add Netlify to Angular Apollo Tailwind showcase

- starter-dev-backend/src/server.js
Per debugging this error:
We got these logs:
which indicate we needed to actually import "path" in node 16.
> add missing path import to server

- qwik-graphql-tailwind/src/components/repo-card/repo-card.tsx
> feat(qwik): Clicking in top repo card is not being redirected

- svelte-kit-scss/src/lib/components/RepositoryList/RepositoryListFilters/SearchInputDelayed.svelte
Resolves: #1090
P2: search on profile page takes too long to execute. debounce should be much lower - probably ~300ms
> [svelte-kit-scss] P2: Fix Execution Time For Search On Profile Page

- solidjs-tailwind/src/components/FileExplorer/FileExplorer.jsx
- solidjs-tailwind/src/components/FileExplorer/parseTree.js
> feat(solidjs-pod): fix order on File Explorer

- svelte-kit-scss/src/lib/components/FileExplorer/FileExplorerReadme/FileExplorerReadme.svelte
Fixes #1187
<hr/>
Couldn't replicate the differing width on my system, tested on Opera and Chrome
This PR fixes the border issue
> [svelte-kit-scss] Style README row width to match files row

- svelte-kit-scss/.storybook/preview.js
Resolves: #1287
> 
> # Description
> - Storybook global styles should be the same as application global styles(routes/styles.scss)
> 
> ![Image](https://user-images.githubusercontent.com/1828602/213208283-c19c367a-b1a5-4371-8cec-b7569cbba074.png)
>
> [svelte-kit-scss] Storybook should use the main stylesheet as the app

- next-react-query-tailwind/src/components/NavBar/NavBar.tsx
- next-react-query-tailwind/src/components/UserDropdown/UserDropdown.view.tsx
- next-react-query-tailwind/src/lib/withAuthRedirect.ts
- next-react-query-tailwind/src/pages/api/auth/[...nextauth].ts
- next-react-query-tailwind/src/pages/auth/signin.tsx
- next-react-query-tailwind/src/pages/index.tsx
Initially, we were using the default sign in screen that Next Auth provided for us, and with that we didn't have a way of adding the Netlify badge on that screen. So this PR handles creating a custom sign in screen that Next Auth can use, that we can add the badge onto.
Since I needed to create a new page, I also had to make a few adjustments so that things redirected as a user would expect, and also hid the nav bar on the sign in page so it's not confusing. Becuase the nav bar wouldn't hide completely, I made the background of the sign in page the same dark blue color to match it. 
I've tested everything locally and it all appears to be working - users can sign in and navigate as expected.
Side note: the es-lint ignore rule is because Next wants us to use their `Image` component instead …
> [Next] Fix: Add Netlify badge to sign in screen

- solidjs-tailwind/src/components/PRAndIssuesHeader/PRAndIssuesHeader.jsx
- filters should be able to be reset, should be able to click on a selected filter and deselect it after it's been selected, or have the option to Select all.
- when clicking the "X" none of the filters or filtered results are cleared. It doesn't appear to be doing anything currently.
How it works is when you click on a filter option twice it resets to the default, for example; for sort option the default is newest while for label option the default on nothing..
> Solidjs: filter option works as expected

- qwik-graphql-tailwind/src/components/pull-request-issue-tab/pull-request-issue-tab.tsx
- qwik-graphql-tailwind/src/routes/[owner]/[name]/issues/index@named.tsx
Fix some missing fields for Issues Store and hide the label filter from the header when we have no label option to show (in order not to have an empty dropdown menu)
Fixes: #1307
> qwik-fix: minor fixes

- solidjs-tailwind/src/components/PRAndIssuesData/PRAndIssuesData.jsx
- solidjs-tailwind/src/components/TabNavigation/TabNavigation.jsx
Fixed header tab highlight in repo page and fixed no result behaviour in issues and prs page (now the header is visible also when we have no results and filter could be deselected)
Fixes: #1313
> solid-fix: header tab in repo page 

- angular-ngrx-scss/src/app/home/home.component.ts
Closes #1295 
The showcase was triggering an API call before it had the user's username, hence why the call was failing. Added a check so that the API call only sends once there's a username to send with it.
> [Angular-NgRx] Fix: API call being made too early

- solidjs-tailwind/src/components/BranchNavigation/BranchNavigation.jsx
- solidjs-tailwind/src/components/FileExplorer/FileExplorer.jsx
- solidjs-tailwind/src/components/RepoFilter/FilterText.jsx
- solidjs-tailwind/src/components/RepoFilter/RepoFilter.jsx
- solidjs-tailwind/src/components/RepoFilter/RepoFilter.module.css
- solidjs-tailwind/src/contexts/RepoContext.jsx
- solidjs-tailwind/src/pages/RepoBlob.jsx
Fixed loading status on every page.
Now when we navigate through repo folders and file, only the page's content is loaded and the header remains visible.
Also, in Profile page, when we set and clear filters only the list of repos is loaded and not the whole page.
Fixes: #1320
> solid-fix: manage loading status on every pages

- solidjs-tailwind/vite.config.js
- When clicking an HTML file to view its contents, a 404 error is currently being returned
> html file shows now

- solidjs-tailwind/vite.config.js
- there is an issue when running `yarn serve`. It goes to port 4173 but then when you authenticate or try to sign in it goes to port 3000. The redirect path is probably wrong and needs to be updated
- configured preview port in vite config to port 3000
Then run this command. You have to run yarn build before you run yarn serve
```bash 
yarn build && yarn serve
```
> changed the review port to 3000 in vite config

- solidjs-tailwind/src/services/get-issues.js
- solidjs-tailwind/src/services/get-repo-pull-requests.js
- solidjs-tailwind/src/services/queries/issue-info.js
- solidjs-tailwind/src/services/queries/repo-pull-requests.js
Now Label Filter on the Prs page and on the issues page is always populated with all the Prs or issues' labels. Also if we select one filter, the dropdown always shows all the options.
Fixes: #1341
> Solidjs-fix: label filter

- amplify.yml
- We use AWS Amplify for our deployments
- If you do not have access to the AWS account, please ask a manager for access
- You should have to modify the `amplify.yaml` in the top-level directory
> Solid start: modified amplify.yml

- solidstart-tanstackquery-tailwind-modules/src/services/get-user-profile.ts
- solidstart-tanstackquery-tailwind-modules/src/services/queries/user-profile.ts
- solidstart-tanstackquery-tailwind-modules/src/types/user-profile-type.ts
Closes: #1352
For the profile page, we want to fairly closely resemble the GitHub user page. This section is focused on the user “card”, where you can see profile information about the user.
> Solidstart/User Profile API

- solidstart-tanstackquery-tailwind-modules/src/services/get-issues.ts
- solidstart-tanstackquery-tailwind-modules/src/services/queries/issue-info.ts
- solidstart-tanstackquery-tailwind-modules/src/types/issues-type.ts
Closes: #1360
On the single repo page, we’ll have a tab for viewing open and closed issues. We do not (currently) have the functionality to click into the issues, so this ticket will be for creating the initial view that mostly concerns the name of the issue and some metadata about each one.
> Issues information API

- solidstart-tanstackquery-tailwind-modules/src/components/RepoFilter/FilterText.tsx
- solidstart-tanstackquery-tailwind-modules/src/components/RepoFilter/RepoFilter.module.css
- solidstart-tanstackquery-tailwind-modules/src/components/RepoFilter/RepoFilter.store.ts
- solidstart-tanstackquery-tailwind-modules/src/components/RepoFilter/RepoFilter.tsx
- solidstart-tanstackquery-tailwind-modules/src/components/RepoFilter/SearchInput.tsx
- solidstart-tanstackquery-tailwind-modules/vite.config.ts
In another ticket, a component was created with various search and filter options. The purpose of this ticket is to dynamically update a line of text that will show below the search / filter component and above the repository list, that gives the user information on how their repositories are filtered and sorted. There should also be a “clear filter” option that shows, that when clicked, removes all filter options and hides this text section.
> search functionality completed

- starter-dev-backend/src/datasources/github-api.ts
- starter-dev-backend/src/schema/github/github.resolvers.ts
- starter-dev-backend/src/schema/github/github.typedefs.ts
- starter-dev-backend/types/graphql.ts
This PR adds a tree subquery on the Repo type that returns a recursive lookup of the entire repo file tree at HEAD. See the test in GraphQL explorer in the screenshot. This will allow users of our GH GraphQL API to create the entire file explorer from their request on the repo query. 
Closes #893
> feat(starter-dev-backend): Adds repo file tree subquery

- cra-rxjs-styled-components/src/context/UserProvider.tsx
This PR adds some logic to only request the user data from the GitHub API after the user has succesfully auth'd and has a token. This prevents failed network requests on the login page and closes #612
> fix(cra-rxjs-sc): Conditionally request user

- solidstart-tanstackquery-tailwind-modules/src/routes/[owner]/[name]/issues.tsx
- solidstart-tanstackquery-tailwind-modules/src/services/get-issues.ts
- solidstart-tanstackquery-tailwind-modules/src/services/get-pull-request.ts
- solidstart-tanstackquery-tailwind-modules/src/types/issues-type.ts
Use always the Label type defined in label-type file
Fixes: #1564
> solidstart-fix: uniformed label type in all the project

- expo-zustand-styled-components/src/components/IssuesTabView/IssuesTabView.styles.ts
- expo-zustand-styled-components/src/components/IssuesTabView/IssuesTabView.tsx
- expo-zustand-styled-components/src/components/PRAndIssueHeader/PRAndIssueHeader.tsx
- expo-zustand-styled-components/src/components/PullRequestsTabView/PullRequestsTabView.styles.ts
- expo-zustand-styled-components/src/components/PullRequestsTabView/PullRequestsTabView.tsx
- expo-zustand-styled-components/src/screens/Repository/Issues/Issues.tsx
- expo-zustand-styled-components/src/screens/Repository/Pull-Requests/Pull-Requests.tsx
- on the issues and on the pr page, when I navigate through pages every time I am in a query loading status the total count number for open and closed issues or pr goes to zero, and then when the query is in the success status we see it again. That number should be fixed and not dependent on all the query statuses.
> open and closed count fixed and empty filter content handled

- expo-zustand-styled-components/src/components/Header/Header.styles.ts
apparently, z-index is all that is needed because of element stacking.
> apparently z-index is all that is needed because of element stacking

- expo-zustand-styled-components/src/components/FileTree/FileTree.styles.ts
- expo-zustand-styled-components/src/components/FileTree/FileTree.tsx
- Styling - we need to place a bit of padding between the file/folder name and its corresponding icon (see image below)
> fix spacing

- expo-zustand-styled-components/src/components/UserDropdown/UserDropdown.tsx
- The first time you log in and click the profile dropdown on the header, the dropdown doesn't show until you refresh the page.
I believe this is due to how the toggle is handled.
> something might be wrong with how zustand store hook works

- expo-zustand-styled-components/src/components/RepoHeading/RepoHeading.tsx
Closes: #1712
- clicking on the repo owner doesn't load the page. We need to check if the repo is for an org or just a user.
https://user-images.githubusercontent.com/36667083/228729721-3dff2ecb-614c-4c5b-a9f6-1e56e0586e85.mp4
> added a check to know the repo is for an org or just a user.

- expo-zustand-styled-components/src/components/LinkButton/LinkButton.tsx
- expo-zustand-styled-components/src/components/PrivacyBadge/PrivacyBadge.tsx
- expo-zustand-styled-components/src/components/RepoHeading/PrivacyIcon.spec.tsx
- expo-zustand-styled-components/src/components/RepoHeading/PrivacyIcon.tsx
- expo-zustand-styled-components/src/components/RepoHeading/RepoHeading.spec.tsx
- expo-zustand-styled-components/src/components/RepoHeading/RepoHeading.tsx
Close: #1741
Found a bug and fixed it `const isPrivate = 'private'.localeCompare(visibility) > 0;`
> test for repo heading and privacy icon

- expo-zustand-styled-components/src/components/IssuePullRequestCard/IssuePullRequestCard.tsx
- expo-zustand-styled-components/src/components/LinkButton/LinkButton.tsx
Closes: #1802
- added an `isBlank` props to handle the link to open in another tab, wasn't able to set target="_blank" directly
- updated issues and PR Link to open in a new tab.
> update LinkButton to handle targe='_blank'

- amplify.yml
- We use AWS Amplify for our deployments
- If you do not have access to the AWS account, please ask a manager for access
- You should have to modify the `amplify.yaml` in the top-level directory
> Setup app deployment

- nuxt3-pinia-vuetify/hooks/useFetchApI.ts
- nuxt3-pinia-vuetify/pages/index.vue
- nuxt3-pinia-vuetify/store/profileStore.ts
- nuxt3-pinia-vuetify/types/users/interface.ts
For the profile page, we want to fairly closely resemble the GitHub user page. This section is focused on the user “card”, where you can see profile information about the user.
> Feat profile api

- nuxt3-pinia-vuetify/hooks/useFetchApI.ts
- nuxt3-pinia-vuetify/nuxt.config.ts
- nuxt3-pinia-vuetify/store/userStore.ts
- nuxt3-pinia-vuetify/types/interfaces.ts
Like the actual GitHub dashboard, we want to show a user their top repositories. The actual dashboard shows some other information, such as event feeds, but these aren’t available via the API easily so we opted for top repositories instead.
- If you’re using the GraphQL API, there’s a TopRepositories query you can run to retrieve this information easily. (example [GraphQL](angular-apollo-tailwind/src/app/gql/queries/user-top-repos.query.gql) )
- If you’re using the REST API, an equivalent query doesn’t exist. We’ve opted to use the following request instead. (example [rest API](angular-ngrx-scss/src/app/user/services/user.service.ts))
> get top repos api

- nuxt3-pinia-vuetify/store/orgStore.ts
There will be a view for an organization’s profile, which, similar to the user’s profile, will list all of the organization’s repositories.
- This query should start sorted by most recently updated.
> get org repos

- nuxt3-pinia-vuetify/store/repoStore.ts
- nuxt3-pinia-vuetify/types/repository/enums.ts
- nuxt3-pinia-vuetify/types/repository/interface.ts
We want to create a view for an individual repository. It will share a similar look to the same page on GitHub, but with slightly fewer features.
> single repo info

- nuxt-pinia-tailwind/components/TheNavBar/TheNavBar.vue
- nuxt-pinia-tailwind/layouts/LoggedIn.vue
As a user, I should see a header with the GitHub logo as a home button on the left, and my user profile picture on the right attached to a dropdown menu. The menu should show links for navigating to my profile and a sign out link.
> chore: added profile dropdown and logout

- .github/workflows/ci-angular-apollo-tailwind.yml
- .github/workflows/ci-angular-ngrx-scss.yml
- .github/workflows/ci-cra-rxjs-styled-components.yml
- .github/workflows/ci-nuxt-pinia-tailwind.yml
- .github/workflows/ci-qwik-graphql-tailwind.yml
- .github/workflows/ci-solidjs-tailwind.yml
- .github/workflows/ci-solidstart-tanstackquery-tailwind-modules.yml
- .github/workflows/ci-svelte-kit-scss.yml
- .github/workflows/ci-vue3-apollo-quasar.yml
- .github/workflows/expo-zustand-styled-components.yml
- .github/workflows/remix-deploy.yml
Node 14 is being deprecated on August 15th 2023 and Angular 16 no longer supports it. The current Node LTS is 18. Therefore I have updated our build actions to no longer use Node 14 and use 16 and/or 18 instead.
> chore: update node versions of build actions

- next-react-query-tailwind/src/components/NavBar/NavBar.stories.tsx
- next-react-query-tailwind/src/components/NavBar/NavBar.tsx
- next-react-query-tailwind/src/pages/[owner]/index.tsx
- next-react-query-tailwind/src/pages/_app.tsx
Now header and profile dropdown menu is visible
Fixes: #1911
> [next-react-query] fix: next react query fixed header and dropdown menu

- cra-rxjs-styled-components/src/App.tsx
- cra-rxjs-styled-components/src/components/repo-filter/SearchInput.tsx
- cra-rxjs-styled-components/src/context/RepoFilterContext.tsx
- cra-rxjs-styled-components/src/helpers/searchFunction.ts
In another ticket, a component was created with a search input field. The purpose of this ticket is to add the functionality to that input. A user should be able to write a query in the input, and the repositories listed on the page should be filtered based on that query after a short debounce time. If the user removes their query, either by clearing all the letters or clicking the X that should appear in the input, the repositories will be reset.
> Cra rxjs search functionality

- solidjs-tailwind/src/components/AuthGuard/AuthGuard.spec.jsx
- solidjs-tailwind/src/components/PRAndIssuesHeader/PRAndIssuesHeader.jsx
- solidjs-tailwind/src/components/PRAndIssuesHeader/utils.jsx
- solidjs-tailwind/src/components/RepoIssues/RepoIssues.jsx
- solidjs-tailwind/src/components/RepoPullRequests/RepoPullRequests.jsx
- solidjs-tailwind/src/contexts/PrAndIssuesContext.jsx
- solidjs-tailwind/src/services/api.js
- solidjs-tailwind/src/services/get-issues.js
- solidjs-tailwind/src/services/get-repo-pull-requests.js
- solidjs-tailwind/src/services/queries/repo-pull-requests.js
- solidjs-tailwind/src/utils/constants.js
- solidjs-tailwind/src/utils/parseFunctions.js
- solidjs-tailwind/src/utils/parseRestAPIPullRequest.js
was able to make milestone work for the Issues tab but apparently, we can't filter by milestones for pull requests with the Graphql API, so we used REST API to achieve the milestone filter functionality
Issue Tab
https://www.awesomescreenshot.com/video/20111107?key=03f2a8c5ec849e5d843422e4e6bffb90
Pull requests Tab
https://www.awesomescreenshot.com/video/20133828?key=53b25f598262c011b0f566a81815ca95
> chore: milestone works for only issues

- angular-ngrx-scss/src/app/fixtures/repository.fixtures.ts
- angular-ngrx-scss/src/app/issues/components/issues-header/issues-header.component.html
- angular-ngrx-scss/src/app/issues/components/issues-header/issues-header.component.scss
- angular-ngrx-scss/src/app/issues/components/issues-header/issues-header.component.ts
- angular-ngrx-scss/src/app/issues/components/issues-list/issues-list.component.html
- angular-ngrx-scss/src/app/issues/components/issues-list/issues-list.component.ts
- angular-ngrx-scss/src/app/issues/components/issues.component.html
- angular-ngrx-scss/src/app/issues/components/issues.component.scss
- angular-ngrx-scss/src/app/issues/components/issues.component.ts
- angular-ngrx-scss/src/app/pull-requests/components/pull-requests-header/pull-requests-header.component.ts
- angular-ngrx-scss/src/app/pull-requests/pull-requests.component.ts
- angular-ngrx-scss/src/app/repository/components/repo-header/repo-header.component.ts
- angular-ngrx-scss/src/app/repository/services/repository.interfaces.ts
- angular-ngrx-scss/src/app/repository/services/repository.service.spec.ts
- angular-ngrx-scss/src/app/repository/services/repository.service.ts
- angular-ngrx-scss/src/app/shared/components/filter-dropdown/filter-dropdown.component.ts
- angular-ngrx-scss/src/app/shared/components/pagination/pagination.component.html
- angular-ngrx-scss/src/app/shared/components/pagination/pagination.component.scss
- angular-ngrx-scss/src/app/shared/components/pagination/pagination.component.ts
- angular-ngrx-scss/src/app/shared/constants/index.ts
- angular-ngrx-scss/src/app/state/repository/repository.actions.ts
- angular-ngrx-scss/src/app/state/repository/repository.effects.spec.ts
- angular-ngrx-scss/src/app/state/repository/repository.effects.ts
- angular-ngrx-scss/src/app/state/repository/repository.reducer.ts
- angular-ngrx-scss/src/app/state/repository/repository.selectors.ts
- angular-ngrx-scss/src/app/state/repository/repository.state.ts
- angular-ngrx-scss/tsconfig.json
> [angular-ngrx-scss] issues tab
