thisdot/starter.dev-github-showcases

vue3-ts-quasar/src/components/GistsPanel/GistsPanel.stories.js
vue3-ts-quasar/src/components/GistsPanel/GistsPanel.vue
vue3-ts-quasar/src/components/GistsPanel/gists-panel.scss
vue3-ts-quasar/src/components/RepoCard/repocard.scss
vue3-ts-quasar/src/types/Gist.ts
vue3-ts-quasar/src/types/index.ts
vue3-ts-quasar/tests/unit/components/GistsPanel.spec.ts
vue3-ts-quasar/tests/unit/components/NavHeader.spec.ts

Component/gists panel (#125)

---

vue3-ts-quasar/src/App.css
vue3-ts-quasar/src/views/Auth/Auth.stories.js
vue3-ts-quasar/src/views/Auth/Auth.vue
vue3-ts-quasar/tests/unit/pages/Auth.spec.ts

Doesn't yet have the auth functionality though.

Page/auth (#145)

---

vue3-ts-quasar/src/components/RepoCard/index.ts
vue3-ts-quasar/src/components/UserProfileCard/index.ts
vue3-ts-quasar/src/components/index.ts
vue3-ts-quasar/tests/unit/components/Logo.spec.ts
vue3-ts-quasar/tests/unit/components/NavHeader.spec.ts
vue3-ts-quasar/tests/unit/components/RepoCard.spec.ts
vue3-ts-quasar/tests/unit/components/UserAvatar.spec.ts
vue3-ts-quasar/tests/unit/components/UserProfileCard.spec.ts

Had messed this one up by merging into main. [Here's the original PR.](https://github.com/thisdot/starter.dev-github-showcases/pull/162)

[Vue3 + TS + Quasar] refactoring: Added components aggregator

---

.github/workflows/be-deploy.yml

Referenced https://stackoverflow.com/questions/62066641/how-to-install-a-private-npm-github-package-during-sls-deploy

update backend deploy script to install secrets correctly

---

next-react-query-tailwind/package.json
next-react-query-tailwind/src/components/RepoReadMe/RepoReadMe.view.tsx
next-react-query-tailwind/src/styles/globals.css
next-react-query-tailwind/yarn.lock

Improved repo readme #233

---

remix-gql-tailwind/app/routes/login.tsx

Updated login page
closes #240

update login page

---

.github/workflows/ci-angular-apollo-tailwind.yml
angular-apollo-tailwind/README.md
angular-apollo-tailwind/codegen.yml
angular-apollo-tailwind/package.json
angular-apollo-tailwind/src/app/file-viewer/file-explorer-list-container/file-explorer-list-container.component.ts
angular-apollo-tailwind/yarn.lock

[Angular-Apollo-Tailwind] Resolve second level and beyond file tree rendering issues

---

angular-apollo-tailwind/src/app/components/pagination/pagination.component.css
angular-apollo-tailwind/src/app/components/pagination/pagination.component.html
angular-apollo-tailwind/src/app/file-viewer/file-explorer-list/file-explorer-list.component.css
angular-apollo-tailwind/src/app/issues/components/issues-list/issues-list.component.css
angular-apollo-tailwind/src/app/profile/profile-repos-list/profile-repos-list.component.css
angular-apollo-tailwind/src/app/pull-requests/components/pull-requests-list/pull-requests-list.component.css

Resolves #158 
1.Replicate Github Pagination:
https://user-images.githubusercontent.com/15368874/167939467-f5cf10ce-3d66-4da1-9c0f-392cd5de8993.mp4
2. Fix first-of-type  Border Top for profile repos list:
3. Remove border last-of-type file-explorer-list:
4. Fix hover issues list:
https://user-images.githubusercontent.com/15368874/167945626-720094c3-8ffb-4e74-8dae-fc851d3f940e.mp4
5. Fix hover PR list:
https://user-images.githubusercontent.com/15368874/167945268-30acb8fd-760c-45a9-8ac0-52660eabb5b1.mp4

[Angular-Apollo-Tailwind] Fix Tailwind Pseudo Class Issues

---

remix-gql-tailwind/app/components/TabNavigation/TabNavigation.tsx

This should also resolve Issue #244

fixed tab focus only showing on root level

---

remix-gql-tailwind/app/components/UserProfile/OrgList.tsx
remix-gql-tailwind/app/components/UserProfile/UserProfile.stories.tsx
remix-gql-tailwind/app/components/UserProfile/UserProfile.view.tsx
remix-gql-tailwind/app/routes/$user/index.tsx

refactor: tweaks user profile information

---

angular-apollo-tailwind/package.json
angular-apollo-tailwind/src/app/components/toaster/toast/toast.component.html
angular-apollo-tailwind/src/app/components/toaster/toast/toast.component.spec.ts
angular-apollo-tailwind/src/app/components/toaster/toast/toast.component.ts
angular-apollo-tailwind/src/app/components/toaster/toaster.component.html
angular-apollo-tailwind/src/app/components/toaster/toaster.component.spec.ts
angular-apollo-tailwind/src/app/components/toaster/toaster.component.ts
angular-apollo-tailwind/src/app/components/toaster/toaster.model.ts
angular-apollo-tailwind/src/app/components/toaster/toaster.module.ts
angular-apollo-tailwind/src/app/components/toaster/toaster.repo.ts
angular-apollo-tailwind/src/app/components/toaster/toaster.service.spec.ts
angular-apollo-tailwind/src/app/components/toaster/toaster.service.ts
angular-apollo-tailwind/src/app/gql/graphql.module.ts
angular-apollo-tailwind/src/app/home/home.component.html
angular-apollo-tailwind/src/app/home/home.module.ts
angular-apollo-tailwind/yarn.lock

Resolves #69 
Toast Feature Addition:
https://www.loom.com/share/26b3c82afbe64dba824e3e260014eda1

[Angular-Apollo-Tailwind]: Add error handling for Apollo requests

---

cra-rxjs-styled-components/src/components/layouts/Sidebar.tsx
cra-rxjs-styled-components/src/constants/url.constants.ts
cra-rxjs-styled-components/src/hooks/gists/use-gists.ts
cra-rxjs-styled-components/src/interfaces/gists.interfaces.ts
cra-rxjs-styled-components/src/routes/top-repos.tsx

Add Currently Authenticated User's Gists to Sidebar

---

remix-gql-tailwind/app/components/UserRepos/UserRepos.view.tsx

https://www.loom.com/share/9dabcc842f9f428289ad26d193be88d5

Fixed the language menu filter issue

---

remix-gql-tailwind/app/components/UserGists/UserGists.view.tsx

https://www.loom.com/share/608c1f82dc4e43378d7815392f911b7b

Resolved gist not opening properly

---

remix-gql-tailwind/app/lib/queries/RepoReadMe.ts
remix-gql-tailwind/app/routes/$user/$repository/index.tsx
remix-gql-tailwind/app/routes/$user/$repository/tree/$branch/$.tsx

fix: resolves README showing on sub-pages

---

cra-rxjs-styled-components/src/components/layouts/Layout.tsx

Fixed the dashboard background color

---

angular-apollo-tailwind/src/app/repos/components/user-gists/user-gists.component.html

Resolves #288 
https://www.loom.com/share/053bf79bbf7b4fb0b4fdbc0b47e55f69

[Angular + Apollo + Tailwind]: Fix User Gists Error

---

angular-apollo-tailwind/src/app/components/filters/profile-repos-filter-store.ts
angular-apollo-tailwind/src/app/components/filters/repos-filter.store.ts
angular-apollo-tailwind/src/app/gql/queries/org-repos.query.ts
angular-apollo-tailwind/src/app/gql/queries/repo-issues.query.ts
angular-apollo-tailwind/src/app/gql/queries/repo-pulls.query.ts
angular-apollo-tailwind/src/app/gql/queries/user-repos.query.ts
angular-apollo-tailwind/src/app/issues/issues.store.ts
angular-apollo-tailwind/src/app/profile/profile-repos-list/profile-repos.store.ts
angular-apollo-tailwind/src/app/pull-requests/pull-requests.store.ts

Resolves: #286 
1. Fix Org Repos Pagination:
https://www.loom.com/share/2ba0d4560ca24c34bfa6b848419481e1
2. Fix Profile Repos Pagination:
https://www.loom.com/share/e82b867c178b439493406b132afcc536
3. Fix Issues List Pagination:
https://www.loom.com/share/61ee4bb8e39e4477844d7f975d82d246
4. Fix PRs list pagination:
https://www.loom.com/share/f7a9ce67a8e542fba16b1fe7370b15be

[Angular + Apollo + Tailwind] Fix Previous Button Pagination

---

next-react-query-tailwind/src/components/TabNavigation/TabNavigation.tsx

[Next + React Query + Tailwind] Fix tab focus lost when not at root level of repo

---

angular-apollo-tailwind/src/app/gql/queries/repo-details.query.ts
angular-apollo-tailwind/src/app/repos/repo-page.resolver.ts

[Angular-Apollo-Tailwind] Update query and resolver to handle repo details to display description

---

nuxt-pinia-tailwind/store/userStore.ts
nuxt-pinia-tailwind/types/user/interfaces.ts

[Nuxt - Pinia - Tailwind] Get Gists

---

nuxt-pinia-tailwind/schemes/authScheme.ts
nuxt-pinia-tailwind/types/auth/index.ts
nuxt-pinia-tailwind/types/auth/interfaces.ts

[Nuxt - Pinia - Tailwind] Get profile info

---

README.md

[README] Indicate a single implementation as a reference 

---

angular-ngrx-scss/src/app/auth/services/auth.service.spec.ts
angular-ngrx-scss/src/app/auth/services/auth.service.ts
angular-ngrx-scss/src/app/home/nav-bar/nav-bar.component.html
angular-ngrx-scss/src/app/home/nav-bar/nav-bar.component.spec.ts
angular-ngrx-scss/src/app/home/nav-bar/nav-bar.component.ts
angular-ngrx-scss/src/app/state/auth/auth.actions.ts
angular-ngrx-scss/src/app/state/auth/auth.effects.spec.ts
angular-ngrx-scss/src/app/state/auth/auth.effects.ts
angular-ngrx-scss/src/app/state/auth/auth.reducer.ts

- connect header / nav bar button to /logout route
- when clicked, clear user authentication from storage
- redirect to login page on success
Fixes #107

feat(angular-ngrx-scss): add logout functionality

---

angular-apollo-tailwind/src/app/components/repos-filter-dropdown/repos-filter-dropdown.component.html
angular-apollo-tailwind/src/app/profile/components/repos-filters/repos-filters.component.html
angular-apollo-tailwind/src/app/profile/org-about/org-about.component.html
angular-apollo-tailwind/src/app/profile/profile-repos-list/profile-repos-list.component.html
angular-apollo-tailwind/src/app/repos/components/repo-meta/repo-meta.component.html
next-react-query-tailwind/src/components/OrgProfile/OrgProfile.view.tsx
next-react-query-tailwind/src/components/RepoFilters/FilterDropdown.tsx
next-react-query-tailwind/src/components/RepoFilters/RepoFilters.tsx
next-react-query-tailwind/src/components/RepoMeta/RepoMeta.tsx
next-react-query-tailwind/src/components/UserRepos/UserRepos.view.tsx
starter-dev-e2e/cypress/fixtures/org/orgProfile.graphql.json
starter-dev-e2e/cypress/fixtures/org/orgRepos.graphql.json
starter-dev-e2e/cypress/fixtures/repo/repoPage.graphql.json
starter-dev-e2e/cypress/integration/organization.spec.ts
starter-dev-e2e/cypress/support/index.ts
starter-dev-e2e/cypress/utils/graphql-test-utils.ts
starter-dev-e2e/cypress/utils/interceptors.json

[Cypress] Add organization page cypress tests

---

angular-apollo-tailwind/src/app/pull-requests/components/pull-requests-empty/pull-requests-empty.component.ts
next-react-query-tailwind/src/components/RepoReadMe/Empty.tsx
starter-dev-e2e/cypress/e2e/dashboard.cy.ts
starter-dev-e2e/cypress/e2e/organization.cy.ts
starter-dev-e2e/cypress/e2e/profile.cy.ts
starter-dev-e2e/cypress/e2e/repo.cy.ts
starter-dev-e2e/cypress/fixtures/repo/graphql/empty/repoIssues.empty.graphql.json
starter-dev-e2e/cypress/fixtures/repo/graphql/empty/repoPage.empty.graphql.json
starter-dev-e2e/cypress/fixtures/repo/graphql/empty/repoPullRequests.empty.graphql.json
starter-dev-e2e/cypress/fixtures/repo/graphql/empty/repoReadMe.empty.graphql.json
starter-dev-e2e/cypress/fixtures/repo/graphql/empty/repoTree.empty.graphql.json
starter-dev-e2e/cypress/support/commands.ts
starter-dev-e2e/cypress/utils/intercept-response.ts
starter-dev-e2e/cypress/utils/interceptors.json

[Cypress] Add empty list tests for repo page

---

angular-apollo-tailwind/src/app/components/filter-dropdown/filter-dropdown.component.html
angular-apollo-tailwind/src/app/issues/issues.component.html
angular-apollo-tailwind/src/app/pull-requests/pull-requests.component.html
next-react-query-tailwind/src/components/FilterDropdown/FilterDropdown.tsx
next-react-query-tailwind/src/components/IssuesContainer/IssuesContainer.tsx
remix-gql-tailwind/app/components/IssuesContainer/IssuesContainer.tsx
starter-dev-e2e/cypress/e2e/repo.cy.ts
starter-dev-e2e/cypress/fixtures/repo/graphql/repoIssues-filterByLabel.graphql.json
starter-dev-e2e/cypress/fixtures/repo/graphql/repoIssues-filterByMilestone.graphql.json
starter-dev-e2e/cypress/fixtures/repo/graphql/repoIssues-sortByAsc.graphql.json
starter-dev-e2e/cypress/fixtures/repo/graphql/repoPullRequests-filterByLabel.graphql.json
starter-dev-e2e/cypress/fixtures/repo/graphql/repoPullRequests-sortByAsc.graphql.json
starter-dev-e2e/cypress/utils/graphql-test-utils.ts
starter-dev-e2e/cypress/utils/interceptors.json

[Cypress] Add filter query tests to repo page

---

angular-ngrx-scss/src/app/auth/redirect/redirect.component.ts
angular-ngrx-scss/src/app/auth/services/auth.guard.spec.ts
angular-ngrx-scss/src/app/auth/services/auth.guard.ts
angular-ngrx-scss/src/app/auth/services/auth.service.ts
angular-ngrx-scss/src/app/state/auth/auth.actions.ts
angular-ngrx-scss/src/app/state/auth/auth.effects.spec.ts
angular-ngrx-scss/src/app/state/auth/auth.effects.ts
angular-ngrx-scss/src/app/state/auth/auth.reducer.ts
starter-dev-backend/.env.example
starter-dev-backend/handler.js
starter-dev-backend/package.json
starter-dev-backend/serverless.yml

Resolves #331 
Adjusted the login logic to both:
- Allow PR previews to work, by checking the url host and adjusting the redirect url if it matches the pr preview url
- Adjusting the auth guard to check for the session cookie instead of relying directly on the store, so page refreshes while a user is still logged in will work
Also adjusted the related tests to work with these changes.

[Angular-NgRx-SCSS] Adjust login logic

---

angular-ngrx-scss/src/app/auth/auth.component.scss

Small PR to adjust the login component so it fills the page. Also using this as a test for the PR deploy previews to ensure the fix that was merged actually works.

[Angular - NgRx - SCSS] Adjust style for login component to fill page

---

angular-ngrx-scss/src/app/home/profile/org-profile/org-profile.component.scss
angular-ngrx-scss/src/app/home/profile/org-profile/org-profile.component.ts
angular-ngrx-scss/src/app/home/profile/profile-about/profile-about.component.html
angular-ngrx-scss/src/app/home/profile/profile.component.spec.ts
angular-ngrx-scss/src/app/home/profile/user-profile/user-profile.component.scss
angular-ngrx-scss/src/app/home/profile/user-profile/user-profile.component.ts
angular-ngrx-scss/src/app/shared/components/repo-controls/repo-controls.component.html
angular-ngrx-scss/src/app/shared/components/repo-controls/repo-controls.component.scss
angular-ngrx-scss/src/app/shared/components/repo-controls/repo-controls.component.spec.ts
angular-ngrx-scss/src/app/shared/components/repo-controls/repo-controls.component.ts
angular-ngrx-scss/src/app/shared/components/repo-list/repo-list.component.ts
angular-ngrx-scss/src/app/state/profile/profile.actions.ts
angular-ngrx-scss/src/app/state/profile/profile.reducer.ts
angular-ngrx-scss/src/app/state/profile/profile.selectors.ts
angular-ngrx-scss/src/app/state/profile/profile.state.ts
angular-ngrx-scss/src/styles.scss

[angular-ngrx-scss] - Implement search functionality

---

vue3-apollo-quasar/tests/unit/components/AppInput.spec.ts

Test re-written and also new test added.

test: completed test, added an extra test

---

vue3-apollo-quasar/tests/unit/components/ListItem.spec.ts

test: completed test corrections

---

vue3-apollo-quasar/src/components/RepoSubHeader/RepoTabHeader.vue
vue3-apollo-quasar/tests/unit/components/RepoTabHeader.spec.ts

closes #480 
- Removed count
- removed if statement
- used beforeAll method to mount wrapper

test: completed respo tab header test re-writing

---

vue3-apollo-quasar/src/components/IssuePullRequestTab/IssuePullRequestTab.vue
vue3-apollo-quasar/tests/unit/components/IssuePullRequestTab.spec.ts

closes #482 
Test rewritten and all test passes

test: completed rewriting test

---

vue3-apollo-quasar/src/components/ProfilePageLayout/ProfilePageLayout.vue
vue3-apollo-quasar/src/components/UserProfileCard/UserProfileCard.vue
vue3-apollo-quasar/src/router/index.ts
vue3-apollo-quasar/src/router/utils.ts
vue3-apollo-quasar/src/views/Home/Home.vue

chore: route guard added

---

angular-ngrx-scss/src/app/home/profile/org-profile/org-profile.component.scss

[angular-ngrx-scss] - Org profile get too wide

---

angular-ngrx-scss/src/app/issues/components/issues-header/issues-header.component.html
angular-ngrx-scss/src/app/issues/components/issues-header/issues-header.component.scss
angular-ngrx-scss/src/app/issues/components/issues-header/issues-header.component.ts
angular-ngrx-scss/src/app/issues/components/issues-list/issues-list.component.html
angular-ngrx-scss/src/app/issues/components/issues-list/issues-list.component.scss
angular-ngrx-scss/src/app/issues/components/issues-list/issues-list.component.ts
angular-ngrx-scss/src/app/issues/components/issues.component.html
angular-ngrx-scss/src/app/issues/components/issues.component.scss
angular-ngrx-scss/src/app/issues/components/issues.component.ts
angular-ngrx-scss/src/app/issues/issues-routing.module.ts
angular-ngrx-scss/src/app/issues/issues.module.ts
angular-ngrx-scss/src/app/repository/repository-routing.module.ts
angular-ngrx-scss/src/app/shared/components/filter-dropdown/filter-dropdown.component.html
angular-ngrx-scss/src/app/shared/components/filter-dropdown/filter-dropdown.component.scss
angular-ngrx-scss/src/app/shared/components/filter-dropdown/filter-dropdown.component.ts
angular-ngrx-scss/src/app/shared/components/pagination/pagination.component.html
angular-ngrx-scss/src/app/shared/components/pagination/pagination.component.scss
angular-ngrx-scss/src/app/shared/components/pagination/pagination.component.ts
angular-ngrx-scss/src/app/shared/shared.module.ts

[angular-ngrx-scss] - Create single repo issues tab view

---

angular-ngrx-scss/src/app/repository/services/repository.interfaces.ts
angular-ngrx-scss/src/app/repository/services/repository.service.spec.ts
angular-ngrx-scss/src/app/repository/services/repository.service.ts

[Angular - NgRx - SCSS] Get pull request information from GitHub API

---

angular-ngrx-scss/src/app/repository/components/repo-header/repo-header.component.html
angular-ngrx-scss/src/app/repository/components/repo-header/repo-header.component.scss
angular-ngrx-scss/src/app/repository/components/repo-header/repo-header.component.ts
angular-ngrx-scss/src/app/repository/components/repo-header/repo-heading/repo-heading.component.html
angular-ngrx-scss/src/app/repository/components/repo-header/repo-heading/repo-heading.component.scss
angular-ngrx-scss/src/app/repository/components/repo-header/repo-heading/repo-heading.component.ts
angular-ngrx-scss/src/app/repository/components/repo-header/repo-info/repo-info.component.html
angular-ngrx-scss/src/app/repository/components/repo-header/repo-info/repo-info.component.scss
angular-ngrx-scss/src/app/repository/components/repo-header/repo-info/repo-info.component.ts
angular-ngrx-scss/src/app/repository/components/repo-header/repo-navigation/repo-navigation.component.html
angular-ngrx-scss/src/app/repository/components/repo-header/repo-navigation/repo-navigation.component.scss
angular-ngrx-scss/src/app/repository/components/repo-header/repo-navigation/repo-navigation.component.ts
angular-ngrx-scss/src/app/repository/components/repository-details/repository-details.component.html
angular-ngrx-scss/src/app/repository/components/repository-details/repository-details.component.spec.ts
angular-ngrx-scss/src/app/repository/components/repository-details/repository-details.component.ts
angular-ngrx-scss/src/app/repository/repository-routing.module.ts
angular-ngrx-scss/src/app/repository/repository.module.ts
angular-ngrx-scss/src/app/state/repository/repository.selectors.ts

[angular-ngrx-scss] - Create repo header and navigation view

---

cra-rxjs-styled-components/src/App.tsx
cra-rxjs-styled-components/src/components/layouts/ProfileLayout.tsx
cra-rxjs-styled-components/src/components/user-profile/index.tsx
cra-rxjs-styled-components/src/index.tsx
cra-rxjs-styled-components/src/routes/profile.tsx

fix: profile page rendering

---

nuxt-pinia-tailwind/.prettierrc
nuxt-pinia-tailwind/store/orgStore.ts
nuxt-pinia-tailwind/store/repoStore.ts
nuxt-pinia-tailwind/types/repository/enums.ts
nuxt-pinia-tailwind/types/repository/interfaces.ts
nuxt-pinia-tailwind/types/repository/types.ts

[Nuxt - Pinia - Tailwind] Get single repo issues

---

cra-rxjs-styled-components/src/components/repo-meta/RepoMeta.tsx

[CRA-RXJS-SC] - Fix Missing key warning

---

cra-rxjs-styled-components/src/components/dropdown/Dropdown.stories.tsx

[CRA-RXJS-SC] - Add dropdown story

---

cra-rxjs-styled-components/src/components/file-viewer/FileViewer.stories.tsx
cra-rxjs-styled-components/src/components/file-viewer/FileViewer.view.tsx

[CRA-RXJS-SC] - Add File Viewer story

---

cra-rxjs-styled-components/src/components/file-explorer/FileExplorer.stories.tsx

[CRA-RXJS-SC] - Add File Explorer story

---

angular-ngrx-scss/src/app/app.module.ts
angular-ngrx-scss/src/app/home/nav-bar/nav-bar.component.html
angular-ngrx-scss/src/app/shared/components/filter-dropdown/filter-dropdown.component.html
angular-ngrx-scss/src/app/shared/components/filter-dropdown/filter-dropdown.component.ts
angular-ngrx-scss/src/app/shared/directives/click-away.directive.spec.ts
angular-ngrx-scss/src/app/shared/directives/click-away.directive.ts
angular-ngrx-scss/src/app/shared/shared.module.ts

[Angular-NgRx-SCSS] Click Away Directive

---

angular-apollo-tailwind/src/app/components/filters/repos-filter.store.ts
angular-apollo-tailwind/src/app/components/pagination/pagination.component.ts
angular-apollo-tailwind/src/app/issues/issues.component.html
angular-apollo-tailwind/src/app/issues/issues.component.ts
angular-apollo-tailwind/src/app/issues/issues.store.ts
angular-apollo-tailwind/src/app/profile/profile-repos-view/profile-repos.store.ts
angular-apollo-tailwind/src/app/pull-requests/pull-requests.store.ts
angular-apollo-tailwind/src/environments/environment.ts

[Angular+Apollo+Tailwind] 318 Refractor Pagination for query params

---

cra-rxjs-styled-components/src/components/layouts/ProfileLayout.tsx
cra-rxjs-styled-components/src/components/repo-card/RepoCard.styles.tsx
cra-rxjs-styled-components/src/components/user-profile/UserProfile.styles.tsx
cra-rxjs-styled-components/src/components/user-profile/UserProfile.tsx
cra-rxjs-styled-components/src/routes/profile.tsx
cra-rxjs-styled-components/src/routes/user-top-repos.tsx

Closes: #598 
https://www.loom.com/share/67d64062cd4e421ebff1e374567c3ec3

[CRA-RxJs-SC] Fix link to view all repositories

---

cra-rxjs-styled-components/src/components/DetailsDropdown/DetailsDropdown.stories.tsx

feat: adds DetailsDropdown story

---

cra-rxjs-styled-components/README.md

[CRA-RXJS-SC]: Update readme

---

vue3-apollo-quasar/src/components/RepoCard/RepoCard.vue
vue3-apollo-quasar/src/views/Profile/Profile.vue

fix: top repo routes properly

---

vue3-apollo-quasar/src/composables/github/index.ts
vue3-apollo-quasar/src/composables/github/queries/index.ts
vue3-apollo-quasar/src/composables/github/queries/organization-profile.query.ts
vue3-apollo-quasar/src/composables/github/types/OrgsProfile.ts
vue3-apollo-quasar/src/composables/github/types/index.ts
vue3-apollo-quasar/src/composables/github/useOrgProfile.ts
vue3-apollo-quasar/src/router/index.ts
vue3-apollo-quasar/src/views/OrgsProfile/OrgsProfile.vue
vue3-apollo-quasar/src/views/OrgsProfile/index.ts
vue3-apollo-quasar/src/views/index.ts

Added query for getting organization profile details

Org query api

---

cra-rxjs-styled-components/src/components/user-profile/UserProfile.tsx

Check for the avatar url before rendering to prevent a broken link from appearing.
closes #595

[CRA RXJS SC] check for url before rendering avatar

---

nuxt-pinia-tailwind/components/UserGists/UserGists.vue
nuxt-pinia-tailwind/components/UserRepos/UserRepos.vue

feat: create main page layout

---

vue3-apollo-quasar/src/components/GistsPanel/GistsPanel.vue

- fix excess gaps between gists
---

fix excess gaps between gists

---

qwik-graphql-tailwind/src/routes/index.tsx
qwik-graphql-tailwind/src/routes/repositories/index.tsx
qwik-graphql-tailwind/src/routes/repositories/types.ts
qwik-graphql-tailwind/src/utils/constants.ts
qwik-graphql-tailwind/src/utils/queries/top-repos-query.ts
qwik-graphql-tailwind/src/utils/useQuery.ts

feat(qwik): Get Top Repositories from API

---

qwik-graphql-tailwind/package-lock.json
qwik-graphql-tailwind/package.json
qwik-graphql-tailwind/src/components/icons/git-branch.icon.tsx
qwik-graphql-tailwind/src/components/icons/index.ts
qwik-graphql-tailwind/src/components/privacy-badge/index.tsx
qwik-graphql-tailwind/src/components/privacy-badge/privacy-badge.className.ts
qwik-graphql-tailwind/src/components/privacy-badge/privacy-badge.stories.tsx
qwik-graphql-tailwind/src/components/repo-meta/index.tsx
qwik-graphql-tailwind/src/components/repo-meta/repo-meta.className.ts
qwik-graphql-tailwind/src/components/repo-meta/repo-meta.stories.tsx
qwik-graphql-tailwind/src/components/top-repos/index.tsx
qwik-graphql-tailwind/src/components/top-repos/parseQuery.ts
qwik-graphql-tailwind/src/components/top-repos/top-repos-card.tsx
qwik-graphql-tailwind/src/components/top-repos/top-repos.className.ts
qwik-graphql-tailwind/src/components/top-repos/types.ts
qwik-graphql-tailwind/src/routes/homepage.classNames.ts
qwik-graphql-tailwind/src/routes/index.tsx
qwik-graphql-tailwind/src/routes/layout.classNames.ts
qwik-graphql-tailwind/src/routes/layout.tsx
qwik-graphql-tailwind/yarn.lock

Closes https://github.com/thisdot/starter.dev-github-showcases/issues/699

[qwik-graphql-tailwind] feat: Main page layout

---

qwik-graphql-tailwind/src/components/repo-card/index.tsx
qwik-graphql-tailwind/src/components/top-repos/top-repos-card.tsx
qwik-graphql-tailwind/src/routes/repositories/types.ts

repo name
visibility tag (public / private)
description (if available)
main language with color dot
star icon with number of stars on repo
last updated text
optional - star button on right to add a star to the repo (does not need to function yet)
Closes: #702

feat(qwik): Create repository card

---

qwik-graphql-tailwind/src/components/gists/index.tsx
qwik-graphql-tailwind/src/components/gists/parseQuery.ts
qwik-graphql-tailwind/src/components/gists/types.ts
qwik-graphql-tailwind/src/utils/queries/gists-query.ts

Closes: https://github.com/thisdot/starter.dev-github-showcases/issues/706

[feat:qwik] Get gists GitHub API

---

svelte-kit-scss/src/lib/components/Gists/Gists.spec.ts
svelte-kit-scss/src/lib/components/Gists/Gists.stories.ts
svelte-kit-scss/src/lib/components/Gists/Gists.svelte
svelte-kit-scss/src/lib/fixtures/gists.ts
svelte-kit-scss/src/lib/helpers/gists.ts
svelte-kit-scss/src/lib/helpers/index.ts
svelte-kit-scss/src/routes/(authenticated)/(home)/+page.server.ts
svelte-kit-scss/src/routes/(authenticated)/(home)/+page.svelte

Resolves: #676
Result:
> # Create gists panel
> 
> 
> As a user, I should see an unordered list of my gists on the main home page.
> 
> 
> - [x] Gist title
> - [x] unordered list of user gists
> - [x] clicking a gist opens that file in a new tab
> 
> ## Notes

[sveltekit-pod] 13 Create gists panel

---

svelte-kit-scss/src/routes/(authenticated)/(home)/+page.svelte
svelte-kit-scss/src/routes/styles.scss

Resolves: #677 
Result:
> # Create main page layout
> 
> 
> As a user, my main page view should show me my gists and top repositories.
> 
> 
> 
>  - [ ] 2 column layout
>  - [ ] Left side
>     - [ ] gists panel
>  - [ ] Right side
>     - [ ] Top repositories title
>     - [ ] card for each of the users’ top repos
>     - [ ] view all repositories button that navigates to user profile page
> 
> ## Notes

[sveltekit-pod] 15 Create main page layout (top repositories + gists)

---

qwik-graphql-tailwind/src/components/repo-card/types.ts
qwik-graphql-tailwind/src/utils/types.ts

Repo types were accidentally deleted. so adding it back.

Fix repo types

---

svelte-kit-scss/src/lib/components/NavBar/NavBar.svelte

Resolves: #811
>![Image](https://user-images.githubusercontent.com/15368874/199523385-d3af6d5e-f605-40b2-8bcf-9a90d883b889.png)

Fix non-interactive element on click warning

---

qwik-graphql-tailwind/src/components/branch-navigation/branch-navigation.classNames.ts
qwik-graphql-tailwind/src/components/branch-navigation/index.tsx
qwik-graphql-tailwind/src/components/file-explorer/file-explorer.classNames.ts
qwik-graphql-tailwind/src/components/file-explorer/index.tsx
qwik-graphql-tailwind/src/components/file-explorer/types.ts
qwik-graphql-tailwind/src/components/icons/document.icon.tsx
qwik-graphql-tailwind/src/components/icons/folder.icon.tsx
qwik-graphql-tailwind/src/components/icons/index.ts
qwik-graphql-tailwind/src/components/repo-tree/index.tsx
qwik-graphql-tailwind/src/routes/[owner]/[name]/index.tsx

feat(qwik): create single repo code tab view

---

svelte-kit-scss/package-lock.json
svelte-kit-scss/package.json
svelte-kit-scss/src/lib/components/FileExplorer/FileExplorerReadme/FileExplorerReadme.svelte
svelte-kit-scss/src/lib/helpers/repository.ts
svelte-kit-scss/src/routes/(authenticated)/[username]/[repo]/+layout.server.ts
svelte-kit-scss/src/routes/(authenticated)/[username]/[repo]/+page.svelte
svelte-kit-scss/vite.config.ts

Closes: #780 
Result: 
https://www.loom.com/share/973e9bdaf7b04a54aa9650c6d248dbf9
> # Create single repo readme view
> 
> 
> As a user, by default when I navigate to a single repository I land on the code tab. Here I can see the folders and files found in the root directory of the repo and the name of the root branch. I can also see the repo’s readme file below the folder tree.
> 
> 
> - [x] show root readme.md file with list icon next to the title
> 
> ## Notes
>

[sveltekit-pod] 28 Create single repo readme view

---

svelte-kit-scss/package-lock.json
svelte-kit-scss/package.json

Fix issue referenced here: https://thisdot-labs.slack.com/archives/C0475BB41DW/p1666758616346219
This may apply to both showcase and kit

[sveltekit-pod] Fix issues with storybook and npm

---

amplify.yml

feat(svelte-kit-scss): add svelte-kit-scss to amplify

---

amplify.yml

- We use AWS Amplify for our deployments
- If you do not have access to the AWS account, please ask a manager for access
- You should have to modify the `amplify.yaml` in the top-level directory

chore: updated amplify.yml file

---

svelte-kit-scss/src/lib/helpers/repositories.ts
svelte-kit-scss/src/routes/(authenticated)/[username]/+page.server.ts
svelte-kit-scss/src/routes/(authenticated)/[username]/+page.svelte

Resolves: #856
> # Implement sort functionality
> 
> 
> In another ticket, a component was created with the sort dropdown button. The purpose of this ticket is to add the functionality and populate the fields for that button. The options that should be available to the user are listed below - when a user selects an option, the repository list on the page should be sorted to match the selection the user made.
> 
> 
> - [x] Sort options: 
>     - [x] last updated (default) - most recent first 
>     - [x] name - Z-A 
>     - [x] stars - most to least
> - [x] only one selection allowed, noted with a check mark icon
> 
> ## Notes

[sveltekit-pod] 23 Implement sort functionality

---

qwik-graphql-tailwind/src/components/file-explorer/index.tsx
qwik-graphql-tailwind/src/components/repo-header/index.tsx
qwik-graphql-tailwind/src/components/tab-navigation/tab-navigation.tsx
qwik-graphql-tailwind/src/routes/[owner]/[name]/blob/[branch]/[...path]/index.tsx
qwik-graphql-tailwind/src/routes/[owner]/[name]/pulls/index.tsx
qwik-graphql-tailwind/src/routes/layout.tsx

Update repo header component use cases

---

qwik-graphql-tailwind/src/components/header/header.tsx
qwik-graphql-tailwind/src/routes/[owner]/[name]/index.tsx

feat(qwik): Fix routing issue when going to home

---

qwik-graphql-tailwind/src/components/repo-heading/index.tsx

Colour: https://github.com/thisdot/starter.dev-github-showcases/issues/947

[qwik-pod] Removed duplicates header link item

---

solidjs-tailwind/src/components/RepoFilter/FilterDropdown.jsx
solidjs-tailwind/src/components/RepoFilter/RepoFilter.jsx
solidjs-tailwind/src/components/RepoFilter/RepoFilter.store.js
solidjs-tailwind/src/helper/getLanguages.js
solidjs-tailwind/src/helper/language-filter-function.js

In another ticket, a component was created with the language dropdown button. The purpose of this ticket is to add the functionality and populate the fields for that button. The options that should be available to the user are listed below - when a user selects an option, the repository list on the page should be filtered to only include ones that match the user’s selection.

[solidjs-kit] 22 Implement language filter functionality

---

solidjs-tailwind/src/components/RepoFilter/FilterDropdown.jsx
solidjs-tailwind/src/components/RepoFilter/RepoFilter.jsx
solidjs-tailwind/src/components/RepoFilter/RepoFilter.store.js
solidjs-tailwind/src/helper/type-filter-function.js

In another ticket, a component was created with the type dropdown button. The purpose of this ticket is to add the functionality and populate the fields for that button. The options that should be available to the user are listed below - when a user selects an option, the repository list on the page should be filtered to only include ones that match the user’s selection.

[solidjs-kit] 21 Implement type filter functionality

---

solidjs-tailwind/.gitignore
solidjs-tailwind/src/App.jsx
solidjs-tailwind/src/components/OrgAbout/OrgAbout.jsx
solidjs-tailwind/src/components/OrgAbout/OrgAbout.stories.jsx
solidjs-tailwind/src/components/OrgAbout/index.js
solidjs-tailwind/src/components/RepoCard/RepoCard.jsx
solidjs-tailwind/src/components/index.js
solidjs-tailwind/src/pages/OrgProfile.jsx
solidjs-tailwind/src/pages/index.js
solidjs-tailwind/src/routes.js

[Solidjs-Tailwind] Set up organisation layout

---

qwik-graphql-tailwind/src/components/issue-tab-view/issue-tab-view.tsx
qwik-graphql-tailwind/src/components/repo-pulls/data.ts
qwik-graphql-tailwind/src/components/repo-pulls/index.tsx
qwik-graphql-tailwind/src/components/repo-pulls/repo-pulls-data.tsx
qwik-graphql-tailwind/src/context/issue-pr-store.ts
qwik-graphql-tailwind/src/routes/[owner]/[name]/pulls/index.tsx
qwik-graphql-tailwind/src/utils/queries/pull-request.ts

[qwik-pod]: Complete Pull Request Tab Content#909

---

qwik-graphql-tailwind/src/components/user-dropdown/user-dropdown.tsx
qwik-graphql-tailwind/src/routes/[user]/index.tsx
qwik-graphql-tailwind/src/routes/layout.tsx

Closes: https://github.com/thisdot/starter.dev-github-showcases/issues/912

fix page flicking when routing

---

solidjs-tailwind/src/components/UserGists/Container.jsx
solidjs-tailwind/src/components/UserGists/UserGists.jsx
solidjs-tailwind/src/components/UserGists/UserGists.module.css
solidjs-tailwind/src/components/UserGists/index.js
solidjs-tailwind/src/pages/Home.jsx

feat(solidjs): Create gists view

---

qwik-graphql-tailwind/src/components/pull-request-issue-tab/data.ts
qwik-graphql-tailwind/src/components/pull-request-issue-tab/pull-request-issue-tab.tsx
qwik-graphql-tailwind/src/components/repo-pulls/types.ts

feat(qwik-pod): Fix build issues

---

svelte-kit-scss/src/lib/components/ErrorPage/ErrorPage.spec.ts

As a user, I would like the ErrorPage component to have unit tests.

[Sveltekit-pod] Implement Error Page Test

---

svelte-kit-scss/src/lib/components/RepoList/RepoList.spec.ts
svelte-kit-scss/src/lib/components/TopRepositories/TopRepositories.spec.ts

As a user, I would like the RepoList component to have unit tests.

[Sveltekit-pod] Implement Repo List 

---

vue3-apollo-quasar/src/App.vue
vue3-apollo-quasar/src/components/Footer/Footer.stories.ts
vue3-apollo-quasar/src/components/Footer/Footer.vue
vue3-apollo-quasar/src/components/Footer/index.ts
vue3-apollo-quasar/src/components/index.ts
vue3-apollo-quasar/src/views/Auth/Auth.vue

Also adding new storybook component for footer.

feat(#961): Add Netlify badge to Vue Apollo Quasar showcase

---

solidjs-tailwind/src/pages/Home.jsx

feat(solidjs): Add API response to gists view

---

solidjs-tailwind/src/components/Header/Header.jsx
solidjs-tailwind/src/components/UserDropdown/UserDropdown.jsx
solidjs-tailwind/src/helper/constants.js

This PR adds a handler with functioning signout functionality to the 'Sign out' item in the user dropdown menu

feat(solidjs-tailwind): Logout

---

solidjs-tailwind/.storybook/preview.js
solidjs-tailwind/msw/server.js
solidjs-tailwind/pnpm-lock.yaml

Adds MSW setup so it can be used in tests and storybook
Closes: https://github.com/thisdot/starter.dev-github-showcases/issues/993

chore(solidjs-tailwind): Add MSW

---

svelte-kit-scss/src/routes/(authenticated)/[username]/[repo]/+layout.svelte

Remove Max width on repo header

---

starter-dev-backend/netlify.toml
starter-dev-backend/src/server.js

- adds netlify redirect routing
- updates express to use router, not app for configuring URLs (this was the big bug)
- reorganized the file to put middleware config separate from routing
- add back routes that were deleted but apps rely on

fix backend routing issues

---

qwik-graphql-tailwind/src/components/filter-dropdown/filter-dropdown.spec.tsx
qwik-graphql-tailwind/src/components/header/header.spec.tsx
qwik-graphql-tailwind/src/components/issue-pr-card/issue-pr-card.spec.tsx
qwik-graphql-tailwind/src/components/issue-tab-view/issue-tab-view.spec.tsx
qwik-graphql-tailwind/src/components/org-list/org-list.spec.tsx
qwik-graphql-tailwind/src/components/privacy-badge/privacy-badge.spec.tsx
qwik-graphql-tailwind/src/components/profile-nav/profile-nav.spec.tsx
qwik-graphql-tailwind/src/components/pull-request-issue-tab/pull-request-issue-tab.spec.tsx
qwik-graphql-tailwind/src/components/repo-about/repo-about.spec.tsx
qwik-graphql-tailwind/src/components/repo-card/repo-card.spec.tsx
qwik-graphql-tailwind/src/components/repo-filters/repo-filters.spec.tsx
qwik-graphql-tailwind/src/components/repo-header/repo-header.spec.tsx
qwik-graphql-tailwind/src/components/repo-heading/repo-heading.spec.tsx
qwik-graphql-tailwind/src/components/user-profile-card/user-profile-card.spec.tsx
qwik-graphql-tailwind/src/components/user-repos/user-repos.spec.tsx

feat(qwik-pod): Add unit testing on Major components

---

starter-dev-backend/package.json
starter-dev-backend/src/lib/access-token.js
starter-dev-backend/src/lib/refresh-token.js
starter-dev-backend/yarn.lock

Replacing Axios with Node fetch because it doesn't work with Netlify (We don't know why) as you see in the next screenshot we logged the result of the data in axios request using `console.log('Result:', result.data);` and this was the result
it looks like encoded, we tried to set the `responseEncoding` to `utf-8` but no result
This is the result of logging the whole result
this is the same request but with `node-fetch`
the last one looks right, so I removed the axios package and migrated to node-fetch

fix: Netlify backend axios

---

cra-rxjs-styled-components/src/components/readme/Readme.stories.tsx

[CRA-RXJS-SCA]: Add story for Readme

---

qwik-graphql-tailwind/src/components/issue-pr-card/card.tsx

feat(qwik-pod): Fix open issue/pr on other tab

---

svelte-kit-scss/src/routes/(authenticated)/[username]/[repo]/+layout.svelte

[svelte-kit-scss] Add top spacing to issues and pull requests

---

qwik-graphql-tailwind/src/components/issue-tab-view/issue-tab-view.tsx
qwik-graphql-tailwind/src/components/repo-pulls/index.tsx
qwik-graphql-tailwind/src/utils/queries/issues-query.ts
qwik-graphql-tailwind/src/utils/queries/pull-request.ts

feat(qwik-pod): fix count on issues/PR

---

svelte-kit-scss/src/lib/components/IssueSearch/IssueSearchListItem/IssueSearchListItem.svelte
svelte-kit-scss/src/lib/helpers/issues.ts
svelte-kit-scss/src/lib/interfaces/data-contract/github/issues.ts
svelte-kit-scss/src/lib/interfaces/issues.ts
svelte-kit-scss/src/routes/(authenticated)/[username]/[repo]/[issueSearchType=issue_search_type]/+page.server.ts

[svelte-kit-scss] Issues and pull requests should open in a new tab on GitHub

---

qwik-graphql-tailwind/src/components/Loading/loading-pulse-dot.tsx
qwik-graphql-tailwind/src/components/gists/index.tsx
qwik-graphql-tailwind/src/components/top-repos/index.tsx

Added loaded dots component and used for top repos and gists loading status.
Fixes: #1111

feat(qwik-pod): added loading dots for gists and top repos

---

solidjs-tailwind/src/components/Icons/StarIcon.jsx
solidjs-tailwind/src/components/RepoCard/RepoCard.jsx
solidjs-tailwind/src/components/RepoCard/RepoCard.module.css

feat(solidjs): Fix star icon styles

---

qwik-graphql-tailwind/src/components/clear-filter-and-sort-button/index.tsx
qwik-graphql-tailwind/src/components/issue-pr-card/card.tsx
qwik-graphql-tailwind/src/components/issue-tab-view/issue-tab-view.tsx
qwik-graphql-tailwind/src/components/pull-request-issue-tab/pull-request-issue-tab.tsx
qwik-graphql-tailwind/src/components/repo-filters/repo-filters.tsx
qwik-graphql-tailwind/src/components/repo-pulls/data.ts
qwik-graphql-tailwind/src/components/repo-pulls/index.tsx
qwik-graphql-tailwind/src/components/repo-pulls/parseQuery.ts
qwik-graphql-tailwind/src/components/repo-pulls/repo-pulls-data.tsx
qwik-graphql-tailwind/src/components/repo-pulls/types.ts
qwik-graphql-tailwind/src/context/issue-tab-header-dropdown.ts
qwik-graphql-tailwind/src/utils/constants.ts
qwik-graphql-tailwind/src/utils/queries/pull-request.ts

Added filter functionality on the pull request page.
Fixes: #1147

feat(qwik-pod): filters for pull request page

---

qwik-graphql-tailwind/src/components/issue-tab-view/data.ts
qwik-graphql-tailwind/src/components/issue-tab-view/issue-tab-view.tsx
qwik-graphql-tailwind/src/components/issue-tab-view/type.ts
qwik-graphql-tailwind/src/utils/queries/issues-query.ts

feat(qwik-pod): Fix sorting on issues

---

svelte-kit-scss/src/lib/components/FileExplorer/FileExplorerContainer/FileExplorerContainer.svelte

[sveltekit-pod] Fix FileExplorer Padding

---

svelte-kit-scss/src/lib/components/FileViewer/FileViewer.spec.ts
svelte-kit-scss/src/lib/helpers/mocks/file-viewer.ts

Add Fileviewer.svelte Test file

---

qwik-graphql-tailwind/src/components/issue-pr-card/card.tsx
qwik-graphql-tailwind/src/components/issue-tab-view/data.ts
qwik-graphql-tailwind/src/components/issue-tab-view/index.tsx
qwik-graphql-tailwind/src/components/issue-tab-view/issues-data.tsx
qwik-graphql-tailwind/src/components/issue-tab-view/parseQuery.ts
qwik-graphql-tailwind/src/components/issue-tab-view/type.ts
qwik-graphql-tailwind/src/components/pull-request-issue-tab/pr-issue-context-provider.tsx
qwik-graphql-tailwind/src/components/pull-request-issue-tab/pull-request-issue-tab.stories.tsx
qwik-graphql-tailwind/src/components/pull-request-issue-tab/pull-request-issue-tab.tsx
qwik-graphql-tailwind/src/components/repo-pulls/data.ts
qwik-graphql-tailwind/src/components/repo-pulls/index.tsx
qwik-graphql-tailwind/src/components/repo-pulls/types.ts
qwik-graphql-tailwind/src/context/issue-pr-store.ts
qwik-graphql-tailwind/src/utils/queries/issues-query.ts

Added milestone and label filter on issue page
Fixes: #1149

feat(qwik-pod): filter function on issues page

---

qwik-graphql-tailwind/src/routes/layout.tsx

When a user isn't logged in, they should be redirected to the sign in page

[qwik-pod] auth bug

---

svelte-kit-scss/src/lib/components/NavBar/NavBar.spec.ts
svelte-kit-scss/src/lib/components/NavBar/NavBar.svelte

This shows addition of Navbar Unit test.
Tests include:
1. Avatar 
2. Sign out
3. Profile link

[sveltekit-pod]: Navbar Unit test

---

solidjs-tailwind/src/components/FileExplorer/FileExplorer.jsx
solidjs-tailwind/src/components/Icons/ChevronDownIcon.jsx
solidjs-tailwind/src/components/Icons/DocumentIcon.jsx
solidjs-tailwind/src/components/Icons/FolderIcon.jsx
solidjs-tailwind/src/components/Icons/index.js
solidjs-tailwind/src/components/UserDropdown/UserDropdown.jsx

feat(solidjs-pod): Fix styling

---

svelte-kit-scss/src/lib/components/RepositoryList/AllRepositoriesList/AllRepositoriesList.spec.ts
svelte-kit-scss/src/lib/components/RepositoryList/RepositoryList/RepositoryList.spec.ts
svelte-kit-scss/src/lib/components/RepositoryList/TopRepositoriesList/TopRepositoriesList.spec.ts
svelte-kit-scss/src/lib/components/RepositoryList/mocks.ts

[sveltekit-pod] : Repositorylist files Unit tests

---

svelte-kit-scss/src/lib/components/Repository/RepositoryCounters.spec.ts
svelte-kit-scss/src/lib/components/Repository/RepositoryCounters.svelte

[svelte-kit-scss] Change Github nouns to verbs

---

svelte-kit-scss/src/lib/components/FileExplorer/FileExplorerReadme/FileExplorerReadme.svelte

[svelte-kit-scss] need max width for repo overview view

---

solidjs-tailwind/src/components/FileExplorer/FileExplorer.jsx
solidjs-tailwind/src/components/Pagination/Pagination.jsx
solidjs-tailwind/src/components/Pagination/Pagination.module.css
solidjs-tailwind/src/components/Pagination/index.js
solidjs-tailwind/src/components/ProfilePage/ProfilePage.jsx
solidjs-tailwind/src/components/UserRepos/UserRepos.jsx
solidjs-tailwind/src/pages/Profile.jsx

Close: #1218
- Created pagination component
- Added pagination to the profile page

created pagination component and added pagination in profile page

---

svelte-kit-scss/README.md

[svelte-kit-scss] Update README to include getting started and additional info

---

svelte-kit-scss/src/lib/services/repository-service.ts

[svelte-kit-scss] Fix issues count - not displaying correct number currently

---

qwik-graphql-tailwind/src/components/user-repos/types.ts
qwik-graphql-tailwind/src/components/user-repos/user-repos.tsx
qwik-graphql-tailwind/src/routes/[user]/index.tsx
qwik-graphql-tailwind/src/routes/[user]/types.ts
qwik-graphql-tailwind/src/utils/queries/repos-query.ts
qwik-graphql-tailwind/src/utils/queries/user-profile-query.ts

Step to reproduce:
- go to the profile page
- click the next button at the bottom of the repo list
Now pagination should work.
Fixes: #1219 
NB: we still have the "Prev" button problem, but it seems a problem related to GitHub API response (everytime we click the Prev button the API response return pageInfo with wrong values)

fix: pagination in profile page

---

svelte-kit-scss/src/lib/components/Gists/Gists.stories.ts

[sveltekit-pod]: FIx Gists Storybook 

---

svelte-kit-scss/src/lib/components/Gists/Gists.stories.ts
svelte-kit-scss/src/lib/components/shared/Breadcrumbs/Breadcrumbs.stories.ts

fix: Storybook Stories

---

qwik-graphql-tailwind/src/components/issue-pr-card/card.tsx
qwik-graphql-tailwind/src/components/pull-request-issue-tab/pull-request-issue-tab.tsx

- when I select a filter, i can't unselect it (no screenshot) - i expect to be able to click again to toggle a filter
Closes #1256

feat(qwik-pod): Fix unsetting filters

---

angular-ngrx-scss/src/app/auth/services/auth.service.ts
angular-ngrx-scss/src/app/home/profile/profile.component.html
angular-ngrx-scss/src/app/home/profile/profile.component.scss
angular-ngrx-scss/src/app/pull-requests/components/pull-request-card/pull-request-card.component.spec.ts

The Netlify badge was missing from the profile page, so this PR adds the badge to that page. 
Closes #1294

[Angular - NgRx] Fix: add missing netlify badge to profile page

---

solidjs-tailwind/src/components/PRAndIssuesData/PRAndIssuesData.jsx
solidjs-tailwind/src/components/PRAndIssuesHeader/PRAndIssuesHeader.jsx
solidjs-tailwind/src/components/PRAndIssuesHeader/utils.jsx
solidjs-tailwind/src/components/PRAndIssuesListItem/PRAndIssuesListItem.jsx
solidjs-tailwind/src/components/RepoIssues/RepoIssues.jsx
solidjs-tailwind/src/contexts/PrAndIssuesContext.jsx
solidjs-tailwind/src/services/get-issues.js
solidjs-tailwind/src/services/queries/issue-info.js
solidjs-tailwind/yarn.lock

Fix filter on the issues page and added missing milestone filter
Fixes: #1299

solid feat: add milestone filter on the issues page

---

solidjs-tailwind/src/index.css
solidjs-tailwind/src/pages/RepoBlob.jsx
solidjs-tailwind/src/routes.js

- clicking into nested files shows blank page, no file contents. Same on main repo page as well as profile page

solidjs nested file content showing

---

solidjs-tailwind/src/components/PRAndIssueLoaderSkeleton/PRAndIssueLoaderSkeleton.jsx
solidjs-tailwind/src/components/PRAndIssueLoaderSkeleton/index.jsx
solidjs-tailwind/src/components/RepoIssues/RepoIssues.jsx
solidjs-tailwind/src/components/RepoPullRequests/RepoPullRequests.jsx

At the moment there is a Loading... text when every data is being fetched which make the user experience bad. Please add a loader skeleton in stead of the Loading... text

added loader skeleton component

---

cra-rxjs-styled-components/src/context/UserProvider.tsx
cra-rxjs-styled-components/src/hooks/auth/use-set-token.ts

This PR fixes the issue where users are in a constant loading state when first logging in.
closes #1292 
https://user-images.githubusercontent.com/67210629/214130274-dda1f082-806a-4d94-b89a-c138b6a00c74.mov

fix: token not being set during initial login

---

solidjs-tailwind/src/components/UserDropdown/UserDropdown.jsx

feat(solidjs-pod): Fix user dropdown on navigate

---

solidjs-tailwind/src/components/RepoCard/RepoCard.jsx
solidjs-tailwind/src/components/RepoCard/RepoCard.spec.jsx
solidjs-tailwind/src/components/RepoCard/data.js
solidjs-tailwind/src/pages/OrgProfile.jsx
solidjs-tailwind/src/services/queries/org-repos.js

- The title on the repo card in the profile should be just the repo name, not username/reponame
same as above for the org page. The title on the repo card should be just the reponame. currently, it’s even has "/reponame"

repo card corrected

---

solidjs-tailwind/msw/server.js
solidjs-tailwind/package.json
solidjs-tailwind/src/components/AuthGuard/AuthGuard.jsx
solidjs-tailwind/src/components/AuthGuard/AuthGuard.spec.jsx
solidjs-tailwind/src/components/RepoAbout/RepoAbout.spec.jsx

- error returned for AuthGuard component when running `yarn test`
Also needed to rewrite test for repo about component

fixed test for authguard and repo about components

---

solidjs-tailwind/README.md

solid-fix: readme typo

---

solidjs-tailwind/README.md

Fixed scripts in readme file
Fixes: #1337

solid-fix: scripts in readme file

---

solidjs-tailwind/src/components/FileExplorer/FileExplorer.jsx

add click cursor in file explorer

---

.github/workflows/ci-solidstart-tanstackquery-tailwind-modules.yml

We want to review changes in as near real-time as possible. The goal of this is to set up guard rails for development practices and validate features as they’re completed.
You can use existing [CI workflows](https://github.com/thisdot/starter.dev-github-showcases/tree/main/.github/workflows) as a baseline

Solid Start: setup CI

---

solidstart-tanstackquery-tailwind-modules/src/services/get-top-repos.ts
solidstart-tanstackquery-tailwind-modules/src/services/queries/top-repos-query.ts

feat(solidstart): Add top-repos API call

---

solidstart-tanstackquery-tailwind-modules/src/services/get-pull-request.ts
solidstart-tanstackquery-tailwind-modules/src/services/queries/pull-request.ts
solidstart-tanstackquery-tailwind-modules/src/types/label-type.ts
solidstart-tanstackquery-tailwind-modules/src/types/pull-request-type.ts

feat(solidstart): Add pull-request API call

---

solidstart-tanstackquery-tailwind-modules/package.json
solidstart-tanstackquery-tailwind-modules/src/components/Icons/GitBranchIcon.tsx
solidstart-tanstackquery-tailwind-modules/src/components/Icons/StarIcon.tsx
solidstart-tanstackquery-tailwind-modules/src/components/Icons/index.ts
solidstart-tanstackquery-tailwind-modules/src/components/PrivacyBadge/PrivacyBadge.spec.tsx
solidstart-tanstackquery-tailwind-modules/src/components/PrivacyBadge/PrivacyBadge.stories.tsx
solidstart-tanstackquery-tailwind-modules/src/components/PrivacyBadge/PrivacyBadge.tsx
solidstart-tanstackquery-tailwind-modules/src/components/PrivacyBadge/index.ts
solidstart-tanstackquery-tailwind-modules/src/components/RepoCard/RepoCard.module.css
solidstart-tanstackquery-tailwind-modules/src/components/RepoCard/RepoCard.spec.tsx
solidstart-tanstackquery-tailwind-modules/src/components/RepoCard/RepoCard.stories.tsx
solidstart-tanstackquery-tailwind-modules/src/components/RepoCard/RepoCard.tsx
solidstart-tanstackquery-tailwind-modules/src/components/RepoCard/data.ts
solidstart-tanstackquery-tailwind-modules/src/components/RepoCard/index.ts
solidstart-tanstackquery-tailwind-modules/src/components/RepoMeta/RepoMeta.module.css
solidstart-tanstackquery-tailwind-modules/src/components/RepoMeta/RepoMeta.spec.tsx
solidstart-tanstackquery-tailwind-modules/src/components/RepoMeta/RepoMeta.tsx
solidstart-tanstackquery-tailwind-modules/src/components/RepoMeta/index.ts

Added repo card component.
Fixes: #1364

Solidstart-feat: repository card

---

solidstart-tanstackquery-tailwind-modules/src/components/GistPanel/Gists.module.css
solidstart-tanstackquery-tailwind-modules/src/components/GistPanel/Gists.spec.tsx
solidstart-tanstackquery-tailwind-modules/src/components/GistPanel/Gists.stories.tsx
solidstart-tanstackquery-tailwind-modules/src/components/GistPanel/GistsData.tsx
solidstart-tanstackquery-tailwind-modules/src/components/GistPanel/GistsWrapper.tsx
solidstart-tanstackquery-tailwind-modules/src/components/GistPanel/data.ts
solidstart-tanstackquery-tailwind-modules/src/components/GistPanel/index.ts
solidstart-tanstackquery-tailwind-modules/tsconfig.json

As a user, I should see an unordered list of my gists on the main home page.

[solidstart-tanstack-tailwind] 13 Create gists panel

---

qwik-graphql-tailwind/.storybook/preview.ts
solidstart-tanstackquery-tailwind-modules/.eslintrc.json
solidstart-tanstackquery-tailwind-modules/.storybook/preview.cjs
solidstart-tanstackquery-tailwind-modules/package.json
solidstart-tanstackquery-tailwind-modules/src/components/RepoFilter/FilterText.tsx
solidstart-tanstackquery-tailwind-modules/src/services/get-pull-request.ts
solidstart-tanstackquery-tailwind-modules/src/types/pull-request-type.ts
solidstart-tanstackquery-tailwind-modules/src/utils/onclickOutside.ts

Added typescript plugin to eslint and configured it.
Fixed: #1409

solidstart-feat: modified eslint rules adding typescript plugin

---

solidstart-tanstackquery-tailwind-modules/src/auth/AuthStore.ts
solidstart-tanstackquery-tailwind-modules/src/auth/index.ts
solidstart-tanstackquery-tailwind-modules/src/components/ProfilePage/ProfilePage.tsx
solidstart-tanstackquery-tailwind-modules/src/components/RepoActionButtons/CountButtonGroup.tsx
solidstart-tanstackquery-tailwind-modules/src/components/RepoFilter/RepoFilter.tsx
solidstart-tanstackquery-tailwind-modules/src/components/RepoFilter/SearchInput.tsx
solidstart-tanstackquery-tailwind-modules/src/components/UserRepos/UserRepos.tsx
solidstart-tanstackquery-tailwind-modules/src/routes/[login].tsx
solidstart-tanstackquery-tailwind-modules/src/routes/orgs/[login].tsx
solidstart-tanstackquery-tailwind-modules/src/services/get-org-repos.ts
solidstart-tanstackquery-tailwind-modules/src/services/get-user-repos.ts
solidstart-tanstackquery-tailwind-modules/src/services/queries/org-repos.ts
solidstart-tanstackquery-tailwind-modules/src/types/org-repos.ts
solidstart-tanstackquery-tailwind-modules/src/types/user-repo-type.ts
solidstart-tanstackquery-tailwind-modules/src/utils/searchFunction.ts
solidstart-tanstackquery-tailwind-modules/src/utils/useRepoSortFilter.ts

Added repos search functionality in profile page and in org page
Fixes: #1378

Solidstart-feat: search functionality

---

solidjs-tailwind/src/components/UserDropdown/UserDropdown.module.css

removed z index in user dropdown to fix issue

---

README.md
solidstart-tanstackquery-tailwind-modules/README.md

Closes: #1401
Since these are meant to be showcases that anyone can view and use as templates, we want to take some time to add them to the documentation site. We want to include notes on any architecture decisions specific to the tech stack that were made, as well as steps for how to run, build, and test the showcase. A link to the currently deployed site is beneficial as well.
<br>
<br>
<br>
<br>
**Other eventual adds**
(doesn’t need an issue ticket, but just for future notes if we want to go further)

Updated README.md 

---

solidstart-tanstackquery-tailwind-modules/src/routes/[login].tsx

closes: #1474
- The profile page -> [http://localhost:3000/[login]](http://localhost:3000/%5Blogin%5D) should have the loading animation instead of text -> Loading...

added loading animation

---

solidstart-tanstackquery-tailwind-modules/src/components/layout.tsx

Resolves: #1488
- Logging out doesn't redirect user to signin page, in pages other than the home page.

fix logout issue

---

solidstart-tanstackquery-tailwind-modules/src/components/Pagination/Pagination.tsx
solidstart-tanstackquery-tailwind-modules/src/components/layout.tsx
solidstart-tanstackquery-tailwind-modules/src/routes/orgs/[login].tsx

Close: #1476
- Missing pagination also in the organization page (and also tab navigation maybe)

add pagination to in org page and navbar

---

.github/workflows/expo-zustand-styled-components.yml
expo-zustand-styled-components/.eslintignore
expo-zustand-styled-components/.eslintrc.json
expo-zustand-styled-components/.gitignore
expo-zustand-styled-components/.prettierignore
expo-zustand-styled-components/package.json
expo-zustand-styled-components/src/screens/About/About.tsx

expo-feat: setup ci

---

solidstart-tanstackquery-tailwind-modules/.husky/pre-commit
solidstart-tanstackquery-tailwind-modules/package.json

Remove Husky from solid start showcase
Fixes: #1503

solidstart-fix: remove husky

---

solidstart-tanstackquery-tailwind-modules/src/components/FilterDropDown/FilterDropdown.tsx
solidstart-tanstackquery-tailwind-modules/src/components/Icons/CheckIcon.tsx
solidstart-tanstackquery-tailwind-modules/src/components/Icons/index.ts
solidstart-tanstackquery-tailwind-modules/src/components/PRAndIssuesData/PRAndIssuesData.tsx
solidstart-tanstackquery-tailwind-modules/src/components/PRAndIssuesData/index.ts
solidstart-tanstackquery-tailwind-modules/src/components/PRAndIssuesHeader/PRAndIssuesHeader.tsx
solidstart-tanstackquery-tailwind-modules/src/components/PRAndIssuesHeader/index.ts
solidstart-tanstackquery-tailwind-modules/src/components/PRAndIssuesHeader/utils.ts
solidstart-tanstackquery-tailwind-modules/src/components/PRAndIssuesListItem/PRAndIssuesListItem.tsx
solidstart-tanstackquery-tailwind-modules/src/components/PRAndIssuesListItem/index.ts
solidstart-tanstackquery-tailwind-modules/src/components/Pagination/Pagination.tsx
solidstart-tanstackquery-tailwind-modules/src/components/RepoIssues/RepoIssues.tsx
solidstart-tanstackquery-tailwind-modules/src/components/RepoIssues/index.ts
solidstart-tanstackquery-tailwind-modules/src/components/RepoIssues/utils.tsx
solidstart-tanstackquery-tailwind-modules/src/routes/[owner]/[name]/issues.tsx
solidstart-tanstackquery-tailwind-modules/src/services/get-issues.ts
solidstart-tanstackquery-tailwind-modules/src/stores/issues-store.ts
solidstart-tanstackquery-tailwind-modules/src/types/issues-type.ts
solidstart-tanstackquery-tailwind-modules/src/types/user-repo-type.ts

feat: Issues tab view

---

expo-zustand-styled-components/src/hooks/stores/index.ts
expo-zustand-styled-components/src/hooks/stores/useGistsStore.ts
expo-zustand-styled-components/src/services/api.ts
expo-zustand-styled-components/src/services/getGists.ts
expo-zustand-styled-components/src/services/queries/gists.ts
expo-zustand-styled-components/src/types/gists-type.ts

Added Gists api call 
Fixes: #1491

expo-feat: gists api call

---

expo-zustand-styled-components/src/hooks/stores/index.ts
expo-zustand-styled-components/src/hooks/stores/useOrgReposStore.ts
expo-zustand-styled-components/src/screens/Home/Home.tsx
expo-zustand-styled-components/src/services/get-org-repos.ts
expo-zustand-styled-components/src/services/queries/org-repos.ts
expo-zustand-styled-components/src/types/org-repos.ts
expo-zustand-styled-components/src/types/user-repos-type.ts

Added org repos api call
Fixes: #1494

expo feat:org repos api call

---

expo-zustand-styled-components/src/hooks/stores/useAppStore.ts
expo-zustand-styled-components/src/services/get-repo-issues.ts
expo-zustand-styled-components/src/services/get-repo-pull-requests.ts
expo-zustand-styled-components/src/services/queries/pull-requests.ts
expo-zustand-styled-components/src/types/issues-type.ts
expo-zustand-styled-components/src/types/label-type.ts
expo-zustand-styled-components/src/types/pull-requests-type.ts

Added get repo pull requests api call
(missing also one type definition)
Fixes: #1520

expo feat: get repo pulls

---

solidstart-tanstackquery-tailwind-modules/src/components/PRAndIssuesHeader/PRAndIssuesHeader.tsx
solidstart-tanstackquery-tailwind-modules/src/components/RepoHeader/RepoHeader.stories.tsx
solidstart-tanstackquery-tailwind-modules/src/components/RepoIssues/RepoIssues.tsx
solidstart-tanstackquery-tailwind-modules/src/components/RepoPullRequests/RepoPullrequests.tsx
solidstart-tanstackquery-tailwind-modules/src/routes/[owner]/[name]/issues.tsx
solidstart-tanstackquery-tailwind-modules/src/routes/[owner]/[name]/pulls.tsx

Fixed storybook (storybook doesn't accept absolute import, repoheader used navlink but we cannot use solidstart router in storybook so I changed the repoheader component inside storybook)
Fixes: #1560

solidstart-fix: storybook

---

solidstart-tanstackquery-tailwind-modules/src/components/PRAndIssuesHeader/PRAndIssuesHeader.tsx
solidstart-tanstackquery-tailwind-modules/src/components/RepoIssues/RepoIssues.tsx
solidstart-tanstackquery-tailwind-modules/src/components/RepoPullRequests/RepoPullrequests.tsx
solidstart-tanstackquery-tailwind-modules/src/components/TabNavigation/TabNavigation.tsx

Fixed closed tab pagination for both Prs page and issues page.
Also fix some navigation between pages behaviour (resetting active tab when you switch from issues and repo and reset pagination too)
Fixes: #1558

solidstart-fix: closed tab pagination for issues and prs page

---

solidstart-tanstackquery-tailwind-modules/src/components/UserDropdown/UserDropdown.module.css
solidstart-tanstackquery-tailwind-modules/src/routes/orgs/[login].tsx
solidstart-tanstackquery-tailwind-modules/src/types/org-repos.ts

Fixed org link in profile page
Fixes: #1565

solidstart-fix: org link in profile page

---

solidstart-tanstackquery-tailwind-modules/src/components/PRAndIssuesHeader/utils.ts
solidstart-tanstackquery-tailwind-modules/src/components/RepoHeader/RepoHeader.stories.tsx
solidstart-tanstackquery-tailwind-modules/src/components/RepoIssues/utils.tsx
solidstart-tanstackquery-tailwind-modules/src/components/RepoPullRequests/utils.tsx
solidstart-tanstackquery-tailwind-modules/src/services/get-pull-request.ts

Formatted all files
Fixes: #1561

solidstart-fix: formatted files

---

solidstart-tanstackquery-tailwind-modules/src/routes/[owner]/[name]/index.tsx
solidstart-tanstackquery-tailwind-modules/src/routes/[owner]/[name]/issues.tsx
solidstart-tanstackquery-tailwind-modules/src/routes/[owner]/[name]/pulls.tsx

Enhance loading pulse dots component position on pages
Fixes: #1563

solidstart-fix: styling of loading pulse component

---

solidstart-tanstackquery-tailwind-modules/README.md
solidstart-tanstackquery-tailwind-modules/src/components/PRAndIssuesHeader/PRAndIssuesHeader.tsx
solidstart-tanstackquery-tailwind-modules/src/components/RepoIssues/RepoIssues.tsx
solidstart-tanstackquery-tailwind-modules/src/components/RepoPullRequests/RepoPullrequests.tsx
solidstart-tanstackquery-tailwind-modules/src/components/TabNavigation/TabNavigation.tsx
solidstart-tanstackquery-tailwind-modules/src/routes/orgs/[login].tsx

Fixed readme file
Fixes: #1574

solidstart-fix: readme file

---

solidstart-tanstackquery-tailwind-modules/README.md
solidstart-tanstackquery-tailwind-modules/package.json

Fixed readme and the package json file.
Fixes: #1590

solidstart-fix: fix readme and package json file

---

expo-zustand-styled-components/src/components/FilterDropdown/FilterDropdown.styles.ts
expo-zustand-styled-components/src/components/FilterDropdown/FilterDropdown.tsx
expo-zustand-styled-components/src/components/Header/Header.styles.ts
expo-zustand-styled-components/src/components/Icons/RepoBookIcon.tsx
expo-zustand-styled-components/src/components/Profile/Repositories/Repositories.styles.ts
expo-zustand-styled-components/src/components/Profile/Repositories/Repositories.tsx
expo-zustand-styled-components/src/components/Profile/UserCard/UserCard.styles.ts
expo-zustand-styled-components/src/components/RepoFilter/FilterText.tsx
expo-zustand-styled-components/src/components/RepoFilter/RepoFilter.styles.ts
expo-zustand-styled-components/src/components/RepoFilter/RepoFilter.tsx
expo-zustand-styled-components/src/components/UserDropdown/UserDropdown.styles.ts
expo-zustand-styled-components/src/hooks/stores/useRepoFilterStore.ts
expo-zustand-styled-components/src/types/top-repos-type.ts
expo-zustand-styled-components/src/utils/getLanguages.ts
expo-zustand-styled-components/src/utils/languageFilterFunction.ts
expo-zustand-styled-components/src/utils/searchFunction.ts
expo-zustand-styled-components/src/utils/sortRepoFunction.ts
expo-zustand-styled-components/src/utils/typeFilterFunction.ts
expo-zustand-styled-components/src/utils/useRepoSortFiler.ts

Added filter and sort functionalities on the profile page. 
Added also the result text
Fixes #1538 
Fixes #1544 
Fixes #1545 
Fixes #1585

expo-feat: added type and language filter functionality and sort functionality

---

solidstart-tanstackquery-tailwind-modules/package.json

Fixed pnpm run start issue
Fixes: #1596

solidstar-fix: fixed pnpm run start issue

---

expo-zustand-styled-components/package.json
expo-zustand-styled-components/src/components/Icons/ReadmeListIcon.tsx
expo-zustand-styled-components/src/components/RepoReadme/RepoReadme.styles.tsx
expo-zustand-styled-components/src/components/RepoReadme/RepoReadme.tsx

[Expo-Zustand-Styled-Components] feat: single repo README view

---

solidstart-tanstackquery-tailwind-modules/netlify.toml
solidstart-tanstackquery-tailwind-modules/package.json
solidstart-tanstackquery-tailwind-modules/vite.config.ts

app deploy

---

solidstart-tanstackquery-tailwind-modules/src/components/RepoFilter/RepoFilter.tsx

New btn opens a new tab when clicked

new btn opens on new tag

---

solidstart-tanstackquery-tailwind-modules/src/components/PRAndIssuesData/PRAndIssuesData.tsx

clear filter replaces refresh

---

expo-zustand-styled-components/src/screens/Login/Login.tsx

Closes: #1597
https://user-images.githubusercontent.com/49324987/225203588-d53925e9-2124-41cb-a5ef-ae153a1b9ebf.mov

[Expo-Zustand-Styled-Components] fix: Android login

---

solidstart-tanstackquery-tailwind-modules/src/utils/getLanguages.ts

apply sorting to langauge dropdown

---

solidstart-tanstackquery-tailwind-modules/src/components/layout.tsx
solidstart-tanstackquery-tailwind-modules/src/hooks/useGetRepoInfo.ts
solidstart-tanstackquery-tailwind-modules/src/root.tsx
solidstart-tanstackquery-tailwind-modules/src/routes/[owner]/[name]/blob/[branch]/[...path]/index.tsx
solidstart-tanstackquery-tailwind-modules/src/routes/[owner]/[name]/index.tsx
solidstart-tanstackquery-tailwind-modules/src/routes/[owner]/[name]/issues.tsx
solidstart-tanstackquery-tailwind-modules/src/routes/[owner]/[name]/pulls.tsx
solidstart-tanstackquery-tailwind-modules/src/routes/[owner]/[name]/tree/[branch]/[...path]/index.tsx
solidstart-tanstackquery-tailwind-modules/src/routes/[owner]/style.module.css
solidstart-tanstackquery-tailwind-modules/src/routes/signin.tsx

- all projects deployed using Netlify need to have the badge associated with the Open Source license we are using. Learn more here: https://www.netlify.com/legal/open-source-policy/
See the screenshots below for more detail. This affects both the login page and each page in the showcase application.

netlify logo added at the bottom of the pages

---

expo-zustand-styled-components/src/components/FilterDropdown/Dropdown.tsx
expo-zustand-styled-components/src/components/FilterDropdown/FilterDropdown.styles.ts
expo-zustand-styled-components/src/components/FilterDropdown/FilterDropdown.tsx
expo-zustand-styled-components/src/components/IssuePullRequestCard/IssuePullRequestCard.tsx
expo-zustand-styled-components/src/components/PRAndIssueHeader/PRAndIssueHeader.tsx
expo-zustand-styled-components/src/hooks/stores/usePRAndIssueHeaderStore.ts
expo-zustand-styled-components/src/utils/dynamicColor.ts

- The labels for the label dropdown as well as each Pr and issue need to be styled with color. The colors should be implemented in such a way that they allow the text to be visible.

label colors fix

---

expo-zustand-styled-components/src/components/IssuesTabView/IssuesTabView.tsx
expo-zustand-styled-components/src/components/PRAndIssueHeader/PRAndIssueHeader.tsx
expo-zustand-styled-components/src/components/Pagination/Pagination.styles.ts
expo-zustand-styled-components/src/components/Pagination/Pagination.tsx
expo-zustand-styled-components/src/components/Pagination/index.ts
expo-zustand-styled-components/src/components/PullRequestsTabView/PullRequestsTabView.tsx
expo-zustand-styled-components/src/components/RepoSubHeader/RepoSubHeader.tsx
expo-zustand-styled-components/src/hooks/stores/useIssuesStore.ts
expo-zustand-styled-components/src/hooks/stores/usePullRequestsStore.ts

- As part of the final cleanup, we need to implement the functionality to handle pagination in both the issues and PR tabs.

Pagination added for issues and PRs

---

expo-zustand-styled-components/src/components/RepoCard/RepoCard.styles.ts
expo-zustand-styled-components/src/components/RepoCard/RepoMeta.tsx

update repo meta spacing

---

expo-zustand-styled-components/src/components/Header/Header.tsx
expo-zustand-styled-components/src/components/LinkButton/LinkButton.tsx
expo-zustand-styled-components/src/components/Organization/Repositories/Repositories.styles.ts
expo-zustand-styled-components/src/components/Organization/Repositories/Repositories.tsx
expo-zustand-styled-components/src/components/Pagination/Pagination.tsx
expo-zustand-styled-components/src/components/Profile/Repositories/Repositories.styles.ts
expo-zustand-styled-components/src/components/Profile/Repositories/Repositories.tsx
expo-zustand-styled-components/src/components/UserDropdown/UserDropdown.spec.tsx
expo-zustand-styled-components/src/components/UserDropdown/UserDropdown.tsx
expo-zustand-styled-components/src/hooks/stores/useOrgStore.ts
expo-zustand-styled-components/src/screens/Organization/Organization.tsx
expo-zustand-styled-components/src/screens/Profile/Profile.tsx
expo-zustand-styled-components/src/services/get-user-profile.ts
expo-zustand-styled-components/src/types/issues-type.ts
expo-zustand-styled-components/src/types/org-repos.ts
expo-zustand-styled-components/src/types/pull-requests-type.ts
expo-zustand-styled-components/src/types/user-repos-type.ts
expo-zustand-styled-components/types.tsx

Closes:  #1637
Added Pagination in orgs profile and user profile screen
The user menu dropdown component was updated as it hasn't been properly linked, resulting in an undefined path in the URL path.
https://user-images.githubusercontent.com/36667083/228393653-4e280e86-afe4-44ad-8d50-fb457965c04b.mov
https://user-images.githubusercontent.com/36667083/228393670-5635b5f6-fb3d-430c-85e3-160e171d6b71.mp4

pagination add to org profile and user profile

---

expo-zustand-styled-components/src/components/IssuesTabView/IssuesTabView.styles.ts
expo-zustand-styled-components/src/components/Pagination/Pagination.tsx
expo-zustand-styled-components/src/components/PullRequestsTabView/PullRequestsTabView.styles.ts
expo-zustand-styled-components/src/screens/Repository/Issues/Issues.style.tsx
expo-zustand-styled-components/src/screens/Repository/Pull-Requests/Pull-Requests.style.tsx
expo-zustand-styled-components/src/screens/Repository/Pull-Requests/Pull-Requests.tsx

Fixed.
- removed failed css props, used scrollview, fix type issue

removed failed css props, used scrollview, fix type issue

---

expo-zustand-styled-components/src/components/Organization/About/About.styles.ts
expo-zustand-styled-components/src/components/Organization/About/About.tsx
expo-zustand-styled-components/src/components/Profile/UserCard/OrgList.styles.ts
expo-zustand-styled-components/src/components/Profile/UserCard/OrgList.tsx
expo-zustand-styled-components/src/components/UserDropdown/UserDropdown.styles.ts
expo-zustand-styled-components/src/components/UserDropdown/UserDropdown.tsx

- Need to ensure that the URL for whatever we are trying to display is available. If it is not available, there needs to be a placeholder. The property cannot accept an empty string or undefined.

fixing uri warning for image source

---

expo-zustand-styled-components/src/components/RepoActionButtons/RepoActionButtons.tsx

Closes: #1707 
- Watch, Star, and Fork Count are displaying incorrectly

update header counter with right result.

---

expo-zustand-styled-components/src/components/LoaderErrorView/LoaderErrorView.spec.tsx

Added LoaderViewError test
Fix: #1729

expo-feat: added loader view test

---

expo-zustand-styled-components/src/components/RepoAbout/RepoAbout.spec.tsx

Added repo about test
Fix: #1736

expo-feat: added repo about test

---

expo-zustand-styled-components/src/components/FileViewer/FileViewer.test.tsx

[expo-zustand-styledcomponents] FileViewer component test

---

expo-zustand-styled-components/src/components/Pagination/Pagination.spec.tsx

Pagination component test

---

expo-zustand-styled-components/src/components/IssuesPRClearFilter/IssuesPRClearFilter.spec.tsx

[expo-zustand-styled-component] IssuesPRClearFilter test

---

expo-zustand-styled-components/src/components/BranchNavigation/BranchNavigation.test.tsx

[expo-zustand-styledcomponents] BranchNavigation component test

---

expo-zustand-styled-components/src/components/TabNavigation/TabNavigation.spec.tsx

TabNavigation test

---

expo-zustand-styled-components/src/components/IssuePullRequestCard/IssuePullRequestCard.spec.tsx

[expo-zustand-styledcomponents] IssuePullRequestCard component test

---

expo-zustand-styled-components/src/utils/searchFunction.spec.ts

[expo-zustand-styledcomponents] searchFunction.ts function test

---

expo-zustand-styled-components/src/utils/typeFilterFunction.spec.ts

[expo-zustand-styledcomponents] typeFilterFunction.ts function test

---

expo-zustand-styled-components/src/components/FilterDropdown/FilterDropdown.test.tsx

[expo-zustand-styledcomponents] FileDropdown component test

---

expo-zustand-styled-components/src/utils/languageFilterFunction.spec.ts

[expo-zustand-styledcomponents] languageFilterFunction.ts function test

---

expo-zustand-styled-components/src/utils/getLanguages.spec.ts

[expo-zustand-styledcomponents] getLanguages.ts function test

---

expo-zustand-styled-components/src/utils/sortRepoFunction.spec.ts

[expo-zustand-styledcomponents] sortRepoFunction.ts function test

---

expo-zustand-styled-components/src/components/PullRequestsTabView/PullRequestsTabView.spec.tsx

[expo-zustand-styledcomponents]: add PullRequestsTabView test

---

expo-zustand-styled-components/src/components/PullRequestsTabView/PullRequestsTabView.tsx

[expo-zustand-styledcomponents] fix broken PR tab view

---

expo-zustand-styled-components/package.json
expo-zustand-styled-components/src/utils/useRepoSortFilter.test.ts

[expo-zustand-styledcomponents] userRepoSortFilter.ts function test

---

expo-zustand-styled-components/src/components/RepoFilter/RepoFilter.spec.tsx
expo-zustand-styled-components/src/components/RepoFilter/RepoFilter.tsx
expo-zustand-styled-components/src/components/RepoFilter/SearchInput.spec.tsx

Repo filer test

---

expo-zustand-styled-components/src/components/RepoActionButtons/CountButtonGroup.spec.tsx
expo-zustand-styled-components/src/components/RepoActionButtons/CountButtonGroup.tsx
expo-zustand-styled-components/src/components/RepoActionButtons/RepoActionButtons.spec.tsx

wrote test for component

---

expo-zustand-styled-components/src/utils/language-colors.spec.ts

test cases for lang color picker

---

expo-zustand-styled-components/src/utils/dynamicColor.spec.ts

[expo-zustand-styledcomponents] dynamicColor.ts function test

---

expo-zustand-styled-components/src/components/Button/Button.styles.ts
expo-zustand-styled-components/src/components/Button/Button.tsx
expo-zustand-styled-components/src/screens/Login/Login.tsx
expo-zustand-styled-components/src/utils/constants.ts

Closes: #1799
- corrected wrong spelling
- remove space when button isn't loading

Spelling and space fix

---

expo-zustand-styled-components/package.json
expo-zustand-styled-components/src/components/FileTree/FileTree.test.tsx
expo-zustand-styled-components/src/components/FileTree/FileTree.tsx
expo-zustand-styled-components/src/components/LinkButton/LinkButton.tsx
expo-zustand-styled-components/src/screens/Login/Login.tsx
expo-zustand-styled-components/src/services/get-repo-tree.ts

Closes: #1807
- Fix page render
- Fix issue with FileTree component not firing when going back to the root link

Expo fix page refresh

---

solidjs-tailwind/package.json
solidjs-tailwind/src/components/AuthGuard/AuthGuard.spec.jsx

- Fixed showcase kit updating main libraries
- Fixed and improved broken test

Fix: Solid.js + TailwindCSS Showcase 

---

cra-rxjs-styled-components/src/components/pull-request-issue-info/PullRequestInfo.stories.tsx
cra-rxjs-styled-components/src/components/pull-request-issue-info/PullRequestIssueInfo.tsx

[CRA-RXJS-SC]: Add story for PR issue info

---

.github/workflows/send-slack-notification.yml
.github/workflows/thank-contributor.yml

This PR adds the thank you script and slack notification that the framework and starter.dev repos has.

chore: adding GH actions for thank you script and slack notification

---

solidstart-tanstackquery-tailwind-modules/vite.config.ts

Removed unused package from vite config file
Fixes: #1593

solidstart-fix: remove unused package from vite config

---

qwik-graphql-tailwind/src/routes/auth/signin/index.tsx
qwik-graphql-tailwind/src/routes/layout.tsx

feat: added netlify badge

---

next-react-query-tailwind/.gitignore
next-react-query-tailwind/public/mockServiceWorker.js
next-react-query-tailwind/src/components/FileExplorer/FileExplorer.stories.tsx
next-react-query-tailwind/src/components/FileViewer/FileViewer.stories.tsx
next-react-query-tailwind/src/components/Loading/LoadingBulletList.stories.tsx
next-react-query-tailwind/src/components/Loading/LoadingPulseDots.stories.tsx
next-react-query-tailwind/src/components/Loading/LoadingTextLine.stories.tsx
next-react-query-tailwind/src/components/NavBar/NavBar.stories.tsx
next-react-query-tailwind/src/components/NavBar/NavBar.tsx
next-react-query-tailwind/src/components/OrgProfile/OrgProfile.stories.tsx
next-react-query-tailwind/src/components/RepoAboutWidget/RepoAboutWidget.stories.tsx
next-react-query-tailwind/src/components/RepoActionButtons/RepoActionButtons.stories.tsx
next-react-query-tailwind/src/components/RepoHeader/RepoHeader.stories.tsx
next-react-query-tailwind/src/components/RepoHeading/RepoHeading.stories.tsx
next-react-query-tailwind/src/components/RepoIssues/RepoIssues.stories.tsx
next-react-query-tailwind/src/components/RepoNavigation/RepoNavigation.stories.tsx
next-react-query-tailwind/src/components/RepoPage/RepoPage.stories.tsx
next-react-query-tailwind/src/components/RepoPulls/RepoPulls.stories.tsx
next-react-query-tailwind/src/components/RepoReadMe/RepoReadMe.stories.tsx
next-react-query-tailwind/src/components/TabNavigation/TabNavigation.stories.tsx
next-react-query-tailwind/src/components/UserDropdown/UserDropdown.data.tsx
next-react-query-tailwind/src/components/UserDropdown/UserDropdown.stories.tsx
next-react-query-tailwind/src/components/UserGists/UserGists.stories.tsx
next-react-query-tailwind/src/components/UserProfile/LoadingProfile.stories.tsx
next-react-query-tailwind/src/components/UserProfile/UserProfile.stories.tsx
next-react-query-tailwind/src/components/UserRepos/LoadingRepos.stories.tsx
next-react-query-tailwind/src/components/UserRepos/UserRepos.stories.tsx
next-react-query-tailwind/src/components/UserTopRepos/UserTopRepos.stories.tsx
next-react-query-tailwind/src/pages/_app.tsx

Storybook has been updated to v7.
The stories need to be updated from CSF2 to CSF3
The stories need to be updated from CSF2 to CSF3
None
_No response_

chore: csf2 to csf3

---

cra-rxjs-styled-components/src/components/filter-dropdown/FilterDropdown.tsx
cra-rxjs-styled-components/src/components/repo-card/RepoCard.stories.tsx
cra-rxjs-styled-components/src/components/repo-filter/Repofilter.tsx
cra-rxjs-styled-components/src/helpers/typeFilterFunction.ts
cra-rxjs-styled-components/src/interfaces/repositories.interfaces.ts

Created filter type function
Fixes #1906

tdl-1906-[cra-rxjs]-feat: filter type function

---

cra-rxjs-styled-components/src/components/icons/CloseIcon.tsx
cra-rxjs-styled-components/src/components/repo-filter/FilterText.tsx
cra-rxjs-styled-components/src/components/repo-filter/RepoFilter.styles.ts
cra-rxjs-styled-components/src/components/repo-filter/Repofilter.tsx
cra-rxjs-styled-components/src/components/repo-filter/SearchInput.tsx
cra-rxjs-styled-components/src/helpers/typeFilterFunction.ts
cra-rxjs-styled-components/src/hooks/repositories/use-repo-sort-filter.ts
cra-rxjs-styled-components/src/routes/profile.tsx

Added sort and filters functionalities on profile page
Fixes: #1909

tdl-1909-[cra-rxjs]-feat: added sort and filters functionalities on profile page

---

cra-rxjs-styled-components/src/components/layouts/ProfileLayout.tsx
cra-rxjs-styled-components/src/routes/profile.tsx

On profile page user are not able to scroll down

chore: fix scroll

---

cra-rxjs-styled-components/src/components/repo-filter/RepoFilter.styles.ts
cra-rxjs-styled-components/src/components/repo-filter/Repofilter.tsx
cra-rxjs-styled-components/src/components/user-repos/UserRepos.styles.tsx
cra-rxjs-styled-components/src/components/user-repos/UserRepos.tsx
cra-rxjs-styled-components/src/hooks/user-repositories/use-user-repositories.ts
cra-rxjs-styled-components/src/routes/orgs.tsx

Sort filter functionality and UI

chore: repo filter for org Page

---

cra-rxjs-styled-components/src/components/empty-result/EmptyResult.styles.ts
cra-rxjs-styled-components/src/components/empty-result/EmptyResult.tsx
cra-rxjs-styled-components/src/components/icons/IssueIcon.tsx
cra-rxjs-styled-components/src/components/icons/PullRequestIcon.tsx
cra-rxjs-styled-components/src/components/pull-request/pull-request/PullRequest.style.tsx
cra-rxjs-styled-components/src/components/pull-request/pull-request/PullRequest.view.tsx
cra-rxjs-styled-components/src/components/repo-issues/Issues/Issues.view.styles.tsx
cra-rxjs-styled-components/src/components/repo-issues/Issues/Issues.view.tsx

added no result for filters in prs and issues page
Fixes: #1933

tdl-1933-[cra-rxjs-sc]-feat: added no result for filters in prs and issues page

---

solidstart-tanstackquery-tailwind-modules/src/components/PRAndIssuesHeader/PRAndIssuesHeader.tsx
solidstart-tanstackquery-tailwind-modules/src/components/PRAndIssuesHeader/utils.ts
solidstart-tanstackquery-tailwind-modules/src/components/RepoIssues/RepoIssues.tsx
solidstart-tanstackquery-tailwind-modules/src/components/RepoPullRequests/RepoPullrequests.tsx
solidstart-tanstackquery-tailwind-modules/src/routes/[owner]/[name]/issues.tsx
solidstart-tanstackquery-tailwind-modules/src/routes/[owner]/[name]/pulls.tsx
solidstart-tanstackquery-tailwind-modules/src/services/api.ts
solidstart-tanstackquery-tailwind-modules/src/services/get-issues.ts
solidstart-tanstackquery-tailwind-modules/src/services/get-pull-request.ts
solidstart-tanstackquery-tailwind-modules/src/services/queries/pull-request.ts
solidstart-tanstackquery-tailwind-modules/src/store.ts
solidstart-tanstackquery-tailwind-modules/src/types/issues-type.ts
solidstart-tanstackquery-tailwind-modules/src/types/pull-request-type.ts
solidstart-tanstackquery-tailwind-modules/src/utils/constants.ts
solidstart-tanstackquery-tailwind-modules/src/utils/parseFunctions.ts
solidstart-tanstackquery-tailwind-modules/src/utils/parseResrAPIPullRequest.ts

https://www.awesomescreenshot.com/video/20149715?key=e4e0fe44c034e01045dfea5b2ac38935

chore: extended the API to make milestone work for pull request
